### ISSUE TITLE
Log lines from builders are really long

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/build#1069]
Just the description of the logger can be really long today, for instance `[SEVERE] Instance of 'DevCompilerBuilder' on e2e_example|web/sub/main.module: `.

This is partly because of the default `toString` for objects and partly because we include the full primary input id in the description.

We could leave it as is and always add newlines after the description, or we could try to shorten the descriptions in some way, but I think we should do something to clean it up.

**Comment by natebosch** [comment]
I'm in favor of having better toStrings on these builders. I would prefer not to reduce the amount of information we have in these.

**Comment by jakemac53** [comment]
Should we consider trying to add some default cleaning up of the toString, just something really simple to handle this case?

```dart
if (builderString.startsWith("Instance of '")) {
  builderString = builderString.substring("Instance of '".length, builderString.length - 1);
}
```

**Comment by natebosch** [comment]
synced offline, I think what we want to do is to track the builder key all the way through to the BuildAction and use that for the log message instead of the builder's toString.

Some other tweaks we want:
- Avoid `<package>|<package>` for 'simple' builder keys
- Remove package name from asset IDs when they are the root package
- Change asset ID into `package:` format instead of using the `|` format.

**Comment by matanlurey** [comment]
> - Change asset ID into `package:` format instead of using the `|` format.

YES THIS PLEASE GOD THIS.
