### ISSUE TITLE
Pub run causes "Unrecognized uri scheme 'http'"

### ISSUE THREAD

**Issue by davidmorgan** [dart-lang/build#108]
If I launch build/watch with "pub run tool/watch.dart" I see an error like:

[INFO] Build: Unrecognized uri scheme `http` found for library in build script, falling back on full rebuild.

I tweaked it to print the full URI and got:

[INFO] Build: Unrecognized uri scheme `http://localhost:53974/watch.dart` found for library in build script, falling back on full rebuild.

Just "dart tool/watch.dart" doesn't have this problem.

**Comment by jakemac53** [comment]
In general, there shouldn't be a need to `pub run` these scripts. If you do then this is actually the correct behavior, because we can't detect whether or not the build script itself has changed in that scenario (it or any of its dependencies may have had some transforms ran on them). 

That being said I think a better error would be good.

**Comment by davidmorgan** [comment]
Sounds good to me. This had me quite confused :)

**Comment by BlackHC** [comment]
+1 to a better error message, though this issue already helps to explain it :)
