### ISSUE TITLE
Consider ditching custom typedefs for new Function syntax?

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/build#1086]
Since we're all on Dart 2 – a nice way to clean things up?

**Comment by natebosch** [comment]
Any in particular? I usually go without the typedef unless it's useful to give it a name for documentation purposes or to cut back on repetition. There were maybe 1 or 2 that we left in solely because the Function syntax didn't work but I don't think there are many...

**Comment by kevmoo** [comment]
None in particular. Just curious about cleanup...

**Comment by eernstg** [comment]
We did have discussions about an extension (which is also focused on improved readability/conciseness rather than expressibility), namely allowing all forms of types on the right hand side. So we could have stuff like `typedef MyMap<X> = Map<SomeComplicatedTypeThatWeDoNotWantToType, X>;`. If we want to do that it would be a bit twisted to get rid of all forms of `typedef` now.

However, I think it would make sense to get rid of the old form like `typedef void F(int)`, or at least fix it such that this doesn't mean `void Function(dynamic int)`. ;-)

**Comment by jakemac53** [comment]
@eernstg ya this is just for within the `build` package :)

I personally like typedefs for anything I would have to type more than once.

**Comment by kevmoo** [comment]
> I personally like typedefs for anything I would have to type more than once.

Agreed, although they introduce yet another member that needs to be documented – and clutters up docs and auto-complete.

**Comment by kevmoo** [comment]
...and they are something else we need to create a name for...
