### ISSUE TITLE
Extend the list of supported synthetic inputs with `$assets$` or similar

### ISSUE THREAD

**Issue by filiph** [dart-lang/build#1132]
I love the new [synthetic inputs feature](https://github.com/dart-lang/build/blob/master/docs/writing_an_aggregate_builder.md). Currently, only `$lib$`, `$test$` and `$web$` are available. 

This doesn't support the use case when you have non-Dart files (text files, yaml files, images, etc.) that should probably not end up in either of `lib/`, `test/` or `web/`, yet they _are_ inputs for some source generation.

Examples: 
* an app with a lot of rich text content could have that content tracked and saved as `.md` files but, for performance reasons, compiled to HTML (or JSONML, or Flutter `build` methods) ahead of time
* an app with image assets could compile these into optimized images, or even provide classes (widgets / components) that already have width & height set up correctly, so that using these images doesn't reflow layout twice

Flutter puts assets to the [`assets/` directory](https://flutter.io/assets-and-images/). Therefore I assume that's the best option.

cc @matanlurey

**Comment by matanlurey** [comment]
@natebosch @jakemac53 I'm sure there is a good reason, but why not support something like `$package$` (or `$default` to line up elsewhere?) instead of specific folders?

**Comment by natebosch** [comment]
We had discussed `$package$` when we added support for `$lib$` and we mainly didn't implement it because there wasn't an immediate need. I've always been nervous about allowing assets to get generated in a different directory than their primary input. We technically allow it today but don't have any API which _encourages_ it like `$package$` would.

I think we'll probably want to add support, and focus on blocking stuff like outputting to `../some_other_package`.

**Comment by jakemac53** [comment]
Fwiw, the workaround today would be something like this:

`build_extensions: {'lib/$lib$': ['any/path/in/my/package']}`

**Comment by maks** [comment]
I'm sorry if I am missing something, but is the workaround mentioned in the last comment by @jakemac53 able to do what @filiph was asking for in this issue?

I ask because I have exactly the same requirement as Filip mentioned: I have a json file somewhere inside `assets/` for a Flutter app from which I would like to use my builder to generate as dart src file, somewhere inside `lib/` yet currently I am only able to generate the dart output file only inside `assets` alongside the json file which is not ideal.

**Comment by jakemac53** [comment]
Yes - the main limitation is you have to explicitly list each and every output file - you can't set up automatic mapping of files created in one directory and output to another.

**Comment by maks** [comment]
@jakemac53 It would be great if `$assets$` could be added to enable this then. 
Given Flutter is such a big user of Dart and that `$web$` already exists what are the reasons against adding `$assets$`?

Already given it's absense it's [causing package authors to have to recommend app authors break Flutter conventions on location for `assets`](https://github.com/timfreiheit/r_flutter#setup) while other package authors are [ending up re-inventing the wheel](https://github.com/CaiJingLong/flutter_resource_generator) because of the current limitation in build.

[For own modest needs](https://github.com/maks/string_res), I've also had to move the location of json data files out of `assets` and into `lib` just to be able to make use of the build mechanism which with its new integration into Flutters hot-reload is really they premiere way to do source generation for Flutter app projects.

I'm hoping I can make the case that there is already a proven, pent-up demand for this in the Flutter space.

**Comment by jakemac53** [comment]
@maks can you elaborate a bit on exactly what you want to accomplish and how `$assets$` would help? It doesn't actually enable anything you can't already do - but it does make it more intuitive.

If what you need is a way to map arbitrary files under `assets` to corresponding locations under `lib` then you actually need a different feature - something like https://github.com/dart-lang/build/issues/1689.

**Comment by jakemac53** [comment]
Specifically, would this proposal work for you? https://github.com/dart-lang/build/issues/1689#issuecomment-432324515

**Comment by maks** [comment]
Yes sorry I should have been more specific as I was really speaking with 2 use cases in mind.
For the first one as in the case of the package I have written, the need is pretty much for something like the proposal in #1689 where based on a single file in `assets` I want to generate a single file in `lib`, my case is just creating a class of `static consts` that match keys in a json file, used for localisation. So for that I guess I'll take further comments over to #1689.

The second usecase though is for what the `r_flutter` and `flutter_resource_generator` packages need, which is generating a single file in `lib` based on the filenames of multiple files inside `assets`. For those coming from the Android world, this is the functionality we are used to with the generated `R` class that represents android resources of various types. 

For this case I thought `$assets$` would be needed but perhaps I'm not clearly understanding how the synthetic inputs feature works?

Also I can see something simliar being needed based on other attributes of files in `assets` other than filename, eg. image size metadata as per Filipes original second example.

**Comment by natebosch** [comment]
> The second usecase though is for what the `r_flutter` and `flutter_resource_generator` packages need, which is generating a single file in `lib` based on the filenames of multiple files inside `assets`.

> For this case I thought `$assets$` would be needed but perhaps I'm not clearly understanding how the synthetic inputs feature works?

I don't think you should need `$assets$` for this. The synthetic asset IDs are useful for handling the _output_ location. For finding the filenames you can use the globbing API [`findAssets`](https://pub.dev/documentation/build/latest/build/AssetReader/findAssets.html) with a pattern like `Glob('assets/**')`. The primary concern would be whether the assets directory is included in the build at all.  Currently we don't include the assets directory [by default](https://github.com/dart-lang/build/blob/935dba607fe3634d5fc66264a9e24ee578debf3e/build_runner_core/lib/src/generate/options.dart#L23-L34). We should probably file a separate issue about adding that to discuss whether it would be a good idea.

**Comment by maks** [comment]
Thats a good point @natebosch I've added #2571 

But if I understand correctly, isn't the use case I mentioned what an aggregate builder is for? 

That is if I want to generate a single code file based on multiple (or all) files in the `assets` folder? I do know about `findAsset()` but according to the [documentation](https://github.com/dart-lang/build/blob/master/docs/writing_an_aggregate_builder.md#writing-the-builder) isn't it still being used in congunction when writing an aggregate builder so we still need to have `$assets$?

And of course that does still leave the need for something like #1689 since the aggregate builder docs show that you much still output to the same root package as you specifiy inside the `$xxx$`.

**Comment by jakemac53** [comment]
> That is if I want to generate a single code file based on multiple (or all) files in the `assets` folder? I do know about `findAsset()` but according to the [documentation](https://github.com/dart-lang/build/blob/master/docs/writing_an_aggregate_builder.md#writing-the-builder) isn't it still being used in congunction when writing an aggregate builder so we still need to have `$assets$?

The synthetic inputs are only needed when you don't have any other consistent input file to use as a primary input. Its primary purpose in this case is to inform the build system of your desired _outputs_, and not your inputs, as Nate mentioned above.

So if your goal is to output a single file under `lib`, then `$lib$` is actually the synthetic input you want. For instance the build extension configuration to output a file at `lib/src/consts.dart` would be:

```yaml
build_extensions:
  $lib$:
    - src/consts.dart
```

> And of course that does still leave the need for something like #1689 since the aggregate builder docs show that you much still output to the same root package as you specifiy inside the `$xxx$`.

The only case where you actually need #1689 is if you want to output some file under `lib` for every single file under `assets`. If your outputs are well known ahead of time and always the same you shouldn't be blocked today :).

I hope that helps!

**Comment by natebosch** [comment]
Capturing a conversation we had offline:

Our plan is to:
-  add `$package$` and improve our docs to make it clear that `$package$` should only be used for the root package, since it will never show up in other packages.
- maintain `$lib$` and make it clear that it should be used for any builder that applies to all packages, since that is the only directory that can be read or written in non-root packages.
- Remove other synthetic asset IDs from our docs.
- In the next breaking release, drop support for other synthetic asset IDs. `$package$` and `$lib$` cover all use cases.

**Comment by maks** [comment]
Thank you very much for the clarification, I appreciate you taking the time to clarify this for me and my apologies for misunderstanding how this works.

I think this means I can have a go at implementing the functionality I need! :tada: 

The documentation for the aggreagate builders is already very good but perhaps adding something similiar to @jakemac53 comment above would help future builder writers.

And thanks again for looking into this! the future with just `$package$` and `$lib$` and #2573 makes me think of lots of new things I can use builders for.
