### ISSUE TITLE
Add command pub run build_runner run

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/build#1159]
... to mirror `pub run` with builders applied.

**Comment by thosakwe** [comment]
I'm interesting in starting a PR to enable this.

In my head, this could just be a combination of existing functionality. The following is but a cursory guess at what it might entail, assuming you ran `pbr run main`:
* `await commandRunner.run(['build', '--output=build/vm'])`
* `await Isolate.spawnUri(new Uri(path: 'bin/main.dart', ...))`

Or, better explained, my idea is:
* The `pbr run` command could only be used to run scripts in the current package. At least, in theory, this makes sense, as all the builders are ultimately run in the context of this package.
* `pbr run <foo>` would find a file named `bin/foo.dart`. After triggering a `build`, it would then spawn a new Isolate running the file.

Is it reasonable to restrict `pbr run` to just scripts in the `bin` directory? Since that's what `pub` does; the only difference here is that you wouldn't need to explicitly declare which package you're running in, for obvious reasons.

I do think that it would be smart to `build` into an output directory, so that cases like native extensions could find the files they need, especially since you can't `import` from `.dart_tool` without relative paths.

**Comment by jakemac53** [comment]
That would be great if you want to help out! I don't think there are any blockers here, we just haven't gotten a lot of requests for it yet and have been busy doing other Dart 2 and performance related improvements :).

> await commandRunner.run(['build', '--output=build/vm'])

I think we probably would want to output to a `tmp` directory, you can look at the `[test](https://github.com/dart-lang/build/blob/master/build_runner/lib/src/entrypoint/test.dart)` command for inspiration here - it basically does exactly what you have proposed with minor differences.

> await Isolate.spawnUri(new Uri(path: 'bin/main.dart', ...))

I am working on a modular kernel pipeline so we could provide kernel files here eventually (which will start up orders of magnitude faster), but we can easily plug that in once it is ready. You can see the `build_vm_compilers` package for reference - but it currently has some issues with circular dependencies that I am working out. 

> The pbr run command could only be used to run scripts in the current package. At least, in theory, this makes sense, as all the builders are ultimately run in the context of this package.

I think that makes sense, we could allow you to run scripts in other packages too if we wanted, but probably only if the scripts are shipped under the `lib` directory. We could always layer that on later by supporting `package:` uris so I don't think we need to support it initially.

> pbr run <foo> would find a file named bin/foo.dart. After triggering a build, it would then spawn a new Isolate running the file.
> Is it reasonable to restrict pbr run to just scripts in the bin directory? Since that's what pub does; the only difference here is that you wouldn't need to explicitly declare which package you're running in, for obvious reasons.

I am not entirely sold on this, for example both the `benchmark` and `example` directories might contain scripts you would want to run. I think we should probably support any path in the current package. Fwiw, `pub run` actually supports this as well it just isn't commonly used.

> I do think that it would be smart to build into an output directory, so that cases like native extensions could find the files they need, especially since you can't import from .dart_tool without relative paths.

Yes - because the spec for the `.packages` file doesn't allow multiple locations for files we will need to build into an output directory. Eventually I think we need to support a cheaper mechanism for this, but that shouldn't be a blocker here.

**Comment by thosakwe** [comment]
I'm almost done with this, just need to add tests if possible.

One thing I noticed with native extensions is that they attempt to be resolved within the working directory (rather than in a package), but that's an SDK issue, haha.
