### ISSUE TITLE
`pub run build_runner ...` does not complete

### ISSUE THREAD

**Issue by eernstg** [dart-lang/build#1164]
* [x] Dart SDK Version (`dart --version`): Dart VM version: 2.0.0-dev.35.0 (Fri Mar 9 13:09:14 2018 +0100) on "linux_x64"
* [x] What package(s) from this repo you are using, and the version (i.e. `build_runner 0.7.12`): build 0.12.0+2, build_barback 0.5.0+3, build_config 0.2.5, build_resolvers 0.2.0, build_runner 0.8.0, build_test 0.10.1+1.
* [x] Whether you are using Windows, MacOSX, or Linux (if applicable): Linux
* [x] Whether you are using Chrome, Safari, Firefox, Edge (if applicable): N/A
* [x] Any other packages or constraints we should know about: Not that I know of.

In an upcoming version of [reflectable](https://github.com/dart-lang/reflectable/tree/update_gitignore_mar18), I'm trying to use `pub run build_runner build` and `pub run build_runner test`, but none of them will terminate, e.g.:

```
  # This run is from before `pub upgrade`.
  $ pub run build_runner build
  [INFO] Generating build script completed, took 404ms
  [INFO] Building new asset graph completed, took 544ms
  [INFO] Checking for unexpected pre-existing outputs. completed, took 1ms
  [INFO] 18m 48s elapsed, 1/4 actions completed.^C
  ...
  # This run uses the versions listed above.
  $ pub run build_runner test
  [INFO] Generating build script completed, took 466ms
  [INFO] Building new asset graph completed, took 513ms
  [INFO] Checking for unexpected pre-existing outputs. completed, took 2ms
  [INFO] 21m 43s elapsed, 9/24 actions completed.^C
```

This may or may not be a bug (I have no idea what it's doing), but it would be nice to have more information about what it's trying to do during those 18 minutes. At the syscall level we get some hints, and it basically looks like it is waiting:

```
~$ sudo strace -f -p 74228
[sudo] password for eernst: 
strace: Process 74228 attached with 8 threads
[pid 74240] restart_syscall(<... resuming interrupted futex ...> <unfinished ...>
[pid 74238] restart_syscall(<... resuming interrupted futex ...> <unfinished ...>
[pid 74236] futex(0x36c9bec, FUTEX_WAIT_PRIVATE, 2069, NULL <unfinished ...>
[pid 74234] futex(0x36c886c, FUTEX_WAIT_PRIVATE, 7, NULL <unfinished ...>
[pid 74233] futex(0x36c8e0c, FUTEX_WAIT_PRIVATE, 81, NULL <unfinished ...>
[pid 74231] epoll_wait(5,  <unfinished ...>
[pid 74228] futex(0x7ffda5dd53b4, FUTEX_WAIT_PRIVATE, 1, NULL <unfinished ...>
[pid 74232] futex(0x36c90ac, FUTEX_WAIT_PRIVATE, 69, NULL <unfinished ...>
[pid 74231] <... epoll_wait resumed> [{EPOLLIN, {u32=6, u64=6}}], 16, -1) = 1
[pid 74231] read(6, "\1\0\0\0\0\0\0\0", 8) = 8
[pid 74231] futex(0x36f707c, FUTEX_WAKE_OP_PRIVATE, 1, 1, 0x36f7078, FUTEX_OP_SET<<28|0<<12|FUTEX_OP_CMP_GT<<24|0x1) = 1
[pid 74238] <... restart_syscall resumed> ) = 0
[pid 74231] timerfd_settime(6, TFD_TIMER_ABSTIME, {it_interval={tv_sec=0, tv_nsec=0}, it_value={tv_sec=0, tv_nsec=0}},  <unfinished ...>
[pid 74238] futex(0x36f7050, FUTEX_WAKE_PRIVATE, 1) = 0
[pid 74231] <... timerfd_settime resumed> NULL) = 0
[pid 74231] epoll_wait(5,  <unfinished ...>
[pid 74238] rt_sigprocmask(SIG_BLOCK, [PROF], [], 8) = 0
[pid 74238] write(4, "\377\377\377\377\377\377\377\377[\331B\31\0\0\0\0\347\265\212\0\0\0\0\0", 24) = 24
[pid 74231] <... epoll_wait resumed> [{EPOLLIN, {u32=0, u64=0}}], 16, -1) = 1
[pid 74238] rt_sigprocmask(SIG_SETMASK, [],  <unfinished ...>
[pid 74231] read(3,  <unfinished ...>
[pid 74238] <... rt_sigprocmask resumed> NULL, 8) = 0
[pid 74238] futex(0x36c82cc, FUTEX_WAKE_OP_PRIVATE, 1, 1, 0x36c82c8, FUTEX_OP_SET<<28|0<<12|FUTEX_OP_CMP_GT<<24|0x1 <unfinished ...>
[pid 74231] <... read resumed> "\377\377\377\377\377\377\377\377[\331B\31\0\0\0\0\347\265\212\0\0\0\0\0", 576) = 24
[pid 74238] <... futex resumed> )       = 1
[pid 74240] <... restart_syscall resumed> ) = 0
[pid 74238] futex(0x36f707c, FUTEX_WAIT_BITSET_PRIVATE, 24603, {tv_sec=9095, tv_nsec=436109435}, 0xffffffff <unfinished ...>
[pid 74240] futex(0x36c82a0, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
[pid 74231] timerfd_settime(6, TFD_TIMER_ABSTIME, {it_interval={tv_sec=0, tv_nsec=0}, it_value={tv_sec=9090, tv_nsec=535000000}}, NULL) = 0
[pid 74240] <... futex resumed> )       = 0
[pid 74231] epoll_wait(5,  <unfinished ...>
...
```

**Comment by natebosch** [comment]
You could try `dart --observe .dart_tool/build/entrypoint/build.dart build` to see if you can find an issue. Is the future returned by your builder never completing?

We should also look at adding the current running action to the output.

**Comment by natebosch** [comment]
This looks like a deadlock caused by not releasing a Resolver.

What I see is:
- Resolver is fetched [here](https://github.com/dart-lang/reflectable/blob/eb7d34f11cf0c972aaf379f111dcc9cd4f206ce9/lib/src/transformer_implementation.dart#L3765). We're running on multiple inputs concurrently and only the first input picks up the resolver, the rest wait for it to release it.
- We get an INFO log: `reflectable on test/check_literal_transform_test.dart:Ignoring entry point reflectable|test/check_literal_transform_test.dart that does not include the library 'package:reflectable/reflectable.dart'` from [here](https://github.com/dart-lang/reflectable/blob/eb7d34f11cf0c972aaf379f111dcc9cd4f206ce9/lib/src/transformer_implementation.dart#L3772) and return 5 lines later without releasing the lock.

The current way we do logging makes this line easy to miss because by default we write over INFO lines. You can run with `--verbose` to make sure it stays visible.

We can maybe print what actions we're waiting for to make this easier to narrow in on. We probably can't do it always since we don't have an implementation for overwriting multiple lines and we don't want to spam every single action to the log, but perhaps if any action has been running longer than a certain amount of time we can print it.

**Comment by eernstg** [comment]
@natebosch, thanks a lot! I should have discovered those things myself, but I'm certainly in a better position to fix it now. ;-)
