### ISSUE TITLE
build_web_compilers + dart2js: use --packages, not `-p`

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/build#1171]
Breaking with latest dart2js

**Comment by kevmoo** [comment]
Failing example: https://travis-ci.org/dart-lang/build/jobs/353615511

**Comment by pulyaevskiy** [comment]
The workaround from #1172 has also been added to `build_node_compilers` in https://github.com/pulyaevskiy/node-interop/issues/8. 

I just wanted to clarify the issue around `--packages` vs `-p`. Is it blocked because we are waiting for dart2js to implement this new flag or are there other blockers involved?

Also if there are any relevant issues in Dart SDK repo I can subscribe to and track updates, I'd appreciate if someone can share a link (a brief search didn't show any for me).

**Comment by natebosch** [comment]
Fixed by https://github.com/dart-lang/build/pull/1180

`--packages` will be the only supported flag going forward, `-p` or `--package-root` will not be supported anymore.
