### ISSUE TITLE
AssetWriter.write* – return WriteAction (or something)

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/build#1254]
The fact that folks aren't supposed to await writeAsBytes/writeAsString is really annoying – since it's good to await futures.

Could these methods return an instance of

```dart
class WriteAction {
  Future get complete;
}
```

So folks who need to wait can, but the lints to get to them?

**Comment by natebosch** [comment]
It wouldn't solve the problem 100% since looking at the docs would still not be clear whether it's necessary to wait for the `complete` on this class. It would also be a lot of implementations to update...

Other options we've considered:

- Add a separate `AssetWriter` implementation for the "builder author" consumers of this package which returns void, and a `BuildSystemWriter` with the current interface which is what build systems implement and returns the Future
- Don't `implement` AssetWriter and just duplicate the methods on `BuildStep` but return void. This would not impact most users but would remove the "pass a BuildStep as an AssetWriter" case for when you are writing a utility that you know shouldn't need the other capabilities of the build step
- Push on https://github.com/dart-lang/linter/issues/419 and see if we can suppress this lint for calls to this method from `BuildStep`.

The first 2, and the original suggestion, are breaking changes in `build`

**Comment by kevmoo** [comment]
> It wouldn't solve the problem 100% since looking at the docs would still not be clear whether it's necessary to wait for the complete on this class. It would also be a lot of implementations to update...

I think many users (well at least me, especially w/ lints) assume that if it returns a future, it should be awaited.

The trick: does the minimal example require `//ignore:` comments or not. 😄 

I'm all for fixing the linter issue, too.

I realize we don't want to break `build` – although now would be a better time than in 1 month...

**Comment by jakemac53** [comment]
Fwiw, its not really _bad_ in most cases to await that future, its just not _required_. We could just stop telling people not to await it.

**Comment by natebosch** [comment]
We're not planning any changes here.
