### ISSUE TITLE
Failed actions might be getting stuck in the asset graph

### ISSUE THREAD

**Issue by natebosch** [dart-lang/build#1354]
https://gitter.im/dart-lang/angular?at=5ae0b11e2d0e228d7baff65b

If the build fails such that a generated asset node gets marked as a failure, then the build structure changes such that we won't attempt to run that action anymore (but it's still in the graph), we might not be cleaning things up properly.

**Comment by jakemac53** [comment]
Ya this makes sense - maybe instead of clearing the failed actions though we should just only fail the build if it actually required one of the failed actions?

**Comment by corporateselect** [comment]
i think its related:

if you produce a simple syntax error in scss files, like .chip {error}, the build will obviously fail, but if you now correct that error it will still say build failed (but it suceeded) until you delete .dart-tool

**Comment by jakemac53** [comment]
Hmm, that is not the behavior I would expect. We have e2e test coverage for this case which is passing (we create a type error, expect a failed build due to ddc compile failing, then fix the error and expect the next build to pass). I don't think we run that build with --fail-on-severe though which might have a weird interaction.
