### ISSUE TITLE
support for import xxx if (dart.library.js)

### ISSUE THREAD

**Issue by alextekartik** [dart-lang/build#1435]
Sorry if I'm not in proper github repository

Before (in dart sdk 1.24.3) I was able to have (like done dart-sass package)

```
import "interface_none.dart"
    if (dart.library.js) "interface_js.dart"
    if (dart.library.io) "interface_io";
```
and `pub build` was deadling with this fine and it was a nice way to export variable/method for either the dart vm or javascript

When using dart 2.0.0-dev.54 and running from intellij, I now get

```
[SEVERE] build_web_compilers|ddc on lib/bug_if/interface.module:
Error compiling dartdevc module:dart2web|lib/bug_if/interface.ddc.js

[error] Target of URI doesn't exist: 'interface_js.dart'. (package:dart2web/bug_if/interface.dart, line 2, col 13)
[error] Target of URI doesn't exist: 'interface_io.dart'. (package:dart2web/bug_if/interface.dart, line 3, col 13)

Please fix all errors before compiling (warnings are okay).
}
```

Will this be supported in the future?

* Dart SDK Version 2.0.0-dev.54
* build_runner 0.8.8
* build_web_compiler 0.4.0
* Ubuntu 16.04

**Comment by jakemac53** [comment]
See https://github.com/dart-lang/build/issues/1430 (closing as duplicate).

Config specific imports have never been implemented for our modular compilation pipelines because its complicated and we hadn't decided how to deal with it yet. It also wasn't clear if they were going to stick around (in their current form at least) for Dart 2 (see https://github.com/dart-lang/sdk/issues/32960).

We do have a plan now and will be moving forward with it pretty soon it looks like.

**Comment by alextekartik** [comment]
Ok thanks for the response. No problem to deal with it
