### ISSUE TITLE
Need issue labels for each of the sub-packages

### ISSUE THREAD

**Issue by natebosch** [dart-lang/build#145]

**Comment by natebosch** [comment]
We should expect more issues to be filed on this repo as we ramp up usage - having issue labels for the sub-packages will be critical to stay organized.

**Comment by kevmoo** [comment]
Hrm...but just one-per pkg, right?

That'd be easy to automate, me thinks.

**Comment by jakemac53** [comment]
What if we create a project for each and organize them that way?

**Comment by natebosch** [comment]
I don't think we need a project. If you look at some of the issues filed recently they have titles starting with [build], [build_test] - a Label instead like we use in the SDK repo would be more structured.

**Comment by jakemac53** [comment]
If we could easily add them to projects I would disagree, but the ui is currently quite bad for that so I agree a label would be easier probably.

Should we just add single labels for each package (`build`, `build_test`, etc), and use those in combination with the existing labels?

**Comment by natebosch** [comment]
Yeah I think a single label for each that we combine with others would be best. An issue could be tagged with [`pkg-build_test`, `Type: Bug`] for instance.

**Comment by kevmoo** [comment]
On Jan 28, 2017 17:32, "Nate Bosch" <notifications@github.com> wrote:

Yeah I think a single label for each that we combine with others would be
best. An issue could be tagged with [pkg-build_test, Type: Bug] for
instance.


+1

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/dart-lang/build/issues/145#issuecomment-275887471>, or mute
the thread

**Comment by jakemac53** [comment]
done, and added to open issues

**Comment by jakemac53** [comment]
Note that all but 2 issues were related to build_runner. This isn't really surprising, but is worth noting.
