### ISSUE TITLE
`buildStep.findAssets()` for any package?

### ISSUE THREAD

**Issue by nshahan** [dart-lang/build#1499]
The question has come up again for me and I am curious if you can think of any potential blockers for adding a package argument to `buildStep.findAssets()`?

**Comment by natebosch** [comment]
The build_runner underlying reader already supports this.

It might be a little tricker in bazel but I can't think of any outright blockers. It's also a potentially bigger sharp edge in bazel since we don't collect up files for you by default and you'd need to manually enable an aspect to collect them - doing so also can hurt performance of the build since you'd be adding a bunch of inputs that can invalidate the output.

**Comment by jakemac53** [comment]
There are some very concerning performance implications of this.

Essentially, for each file that is added or deleted today we only have to iterate the generated nodes in _that package_ and check the paths against globs they depend on in order to see if they need to be re-ran.

If we allow this feature, then we would have to iterate _all_ generated nodes in _all_ packages, instead of just the package that the new/deleted files belong to. We can mitigate this to some degree by indexing the globs by the package that was globbed, but it still concerns me.

Another option could be changing how we treat globs entirely and not try to be as smart, for instance the second you glob a package you would get invalidated any time any file in that package is added or removed.

**Comment by natebosch** [comment]
I think indexing by package should be fine. In the typical case only the root package is going to get changes and only builders in the root package will glob there. While finding assets in deps the files are unlikely to change.

**Comment by jakemac53** [comment]
> While finding assets in deps the files are unlikely to change.

There are some potential cases such as `pub upgrade` though which can result in a large number of additions/deletions, which is the main case I am concerned about.

Much of the time a pub upgrade will end up in a complete build invalidation anyways - but if it doesn't then a single poorly behaved builder could potentially cause the asset graph invalidation step to take a really long time.

**Comment by matanlurey** [comment]
@jakemac53:

> then a single poorly behaved builder could potentially cause

This sounds like a use-case to help identify/debug poorly "behaved" builders more than preventing this feature, unless I mis-understand. (I realize we have a lot of work to do here still)

**Comment by jakemac53** [comment]
Lets try and make a decision here and close this issue one way or the other?

Pros:
- more powerful builders

Cons:
- bazel support would require using an aspect to collect all transitive files you could potentially ever glob as inputs 
- potential performance issues in build_runner when updating the asset graph for large sets of new/deleted files, or if large numbers of build actions use this feature

Maybe just react to this message with a :+1: or :-1: if you are for or against adding this feature?

**Comment by jakemac53** [comment]
Closing this as not planned for now. We could bring it back up in the future but it isn't on any current roadmaps.
