### ISSUE TITLE
Should it use flush: true for file operations?

### ISSUE THREAD

**Issue by nickclmb** [dart-lang/build#1645]
Hi all, 

On the big projects sometimes we get errors like this:
`lib/$lib$  AssetNotFoundException: wrike_task_list|.dart_tool/build/generated/wrike_task_list/test/src/core/directives/data_template/content_template_test.dart.node_test.dart`

also similar errors we got when running unit tests:
`Failed to load "test/components/survey_renderer_controller_test.dart": Failed to load script at http://localhost:41925/wYZ2VZMnILb4hm9CfnL90Z%2Fo5%2BAoxuHx/test/components/survey_renderer_controller_test.dart.browser_test.dart.js`

These are floating errors, after build done i can see files on disk, and after cleaning up .dart_tool folder they can dissappear, or fail on other assets.

I think that happens because File.writeAsString and writeAsBytes methods executed without `flush: true` flag, so sometimes next action can run before OS write file down to file system.

With enabled `flush: true` it seems like problems dissapear.

So what do you think, it is possible to enable that by default, or make it configurable via build options?

**Comment by jakemac53** [comment]
This is a pretty weird one for sure. Are you running in `--low-resources-mode`? Not using that should actually resolve this issue as it will avoid going to disk at all, but I realize it will have other problems for projects of your size most likely.

If setting `flush: true` fixes things I think we would be ok with changing that, but it sounded like it doesn't fully resolve the issues either?

> Unit test builders run with isOptional: false, and it seems like build_runner reorder non-optional builders with stronglyConnectedComponents function, so they always appear in the end of Build Phases list

I believe that only happens when determining the order for auto-generated build scripts, it shouldn't impact manually written build scripts afaik.

**Comment by nickclmb** [comment]
Hi Jake,

No, we don't use low resources mode, and flush: true didn't help.
So far the build phases has different order, but seems like unit tests builders goes before any meta module builder:
```
...
Unit tests on any assets in wrike_ws [hidden]
Unit tests on any assets in wrike_ws [hidden]
Unit tests on any assets in wrike_ws [hidden]
...
DDC1 - meta on any assets in wrike_ws [optional, hidden]    <-- here it fails, asset not found
...
```
So trying to find any other place with possible race condition

**Comment by natebosch** [comment]
> So far the build phases has different order, but seems like unit tests builders goes before any meta module builder:

Note that the order that builders run in an actual build can be different from the "logical" order of the builders. If a builder is "optional" it won't be run until some other builder requests one of it's outputs. As long as you are going through the `buildStep.readAs*` methods the response will wait for any optional builders to be triggered and complete. The `DD1` builder is `optional`, which means that it could be ordered before the unit test builder, but still run later in practice.

The `AssetNotFound` exception could be fired because of a restricting in reading the asset due to the logical ordering. If it was failing because of this I would expect it to be consistent though...

**Comment by nickclmb** [comment]
Issue resolved
