### ISSUE TITLE
Slow serve and file watching. Safari memory issues

### ISSUE THREAD

**Issue by jasoncapriati** [dart-lang/build#1659]
The `webdev build` and `webdev serve` commands are running slow. Which I figured are using `build`. In comparision `dart2js` builds in milliseconds.

Hello world can take up to 20 seconds on a MacBook. File watch updates can take 5-10 seconds. 

Situation with Chrome for updates is better, but Safari is constantly warning `This webpage is using significant memory`

Log
```
Serving `web` on http://localhost:8080
[INFO] ------------------------------------------------------------------------
[INFO] Starting Build
[INFO] Updating asset graph completed, took 14ms
[INFO] Running build completed, took 11.6s
[INFO] Caching finalized dependency graph completed, took 129ms
[INFO] Succeeded after 11.7s with 5 outputs (4 actions)
```

How can I help debug?

```
Dart VM version: 2.0.0-dev.67.0 (Tue Jul 3 18:17:07 2018 +0200) on "macos_x64"

dev_dependencies:
  build_runner: ^0.9.0
  build_web_compilers: ^0.4.0
```

**Comment by jakemac53** [comment]
Was this the first build after starting up the server or a subsequent one? The first build always incurs significant overhead due to populating the analysis context.

You can also follow [these docs](https://github.com/dart-lang/build/blob/master/docs/measuring_performance.md) to do some further profiling.

**Comment by matanlurey** [comment]
It's also worth mentioning DDC on Safari is not officially supported.

**Comment by march** [comment]
Thanks @jakemac53 and @matanlurey 

Looks like there are some related issues with build_runner and the v2 dev SDK. 

```
Unable to spawn isolate: .dart_tool/pub/bin/build_runner/build_runner.dart.snapshot.dart2:1:1: Error: Unable to decode bytes as UTF-8.
```

The docs also say that initial build is expected to be slow.  There are ways to swap to dart2js. Perhaps stable defaults are better for someone not so savvy with the tooling.

Really enjoying learning Dart. You may this close issue if you wish. I'll check in as the development matures.

**Comment by xavierhainaux** [comment]
> It's also worth mentioning DDC on Safari is not officially supported

Shouldn't the server automatically use Dart2JS or DDC depending on the user agent requesting the page?
More or less like today when "package:browser" detects if the browser support Dart and request the dart script or the JS script. It is very convenient because we can develop in Dartium and other browsers with only 1 "pub serve".

**Comment by matanlurey** [comment]
> Shouldn't the server automatically use Dart2JS or DDC depending on the user agent requesting the page?

No. That would conflict with the point of the build system.

**Comment by xavierhainaux** [comment]
> That would conflict with the point of the build system

OK. 
What is the recommended workflow to develop an application with a fast workflow on Chrome (DDC) but keep the possibility to sometime open the app on Safari or an other mobile browser?

**Comment by jakemac53** [comment]
> What is the recommended workflow to develop an application with a fast workflow on Chrome (DDC) but keep the possibility to sometime open the app on Safari or an other mobile browser?

There isn't a simple solution today that doesn't require stopping your server and rerunning it, either with or without `--release`. 

Note that with pub there was no option to switch compilers on the fly either.

In the long term once we move to a daemon process we might be able to re-evaluate something that lets you change build configuration on the fly without explicitly restarting the server.

**Comment by matanlurey** [comment]
I am not sure this issue is actionable as-is.

Browser support for DDC is documented here:
https://webdev.dartlang.org/tools/dartdevc/faq#what-browsers-does-dartdevc-work-with

If you have the opportunity to [measure build-time performance](https://github.com/dart-lang/build/blob/master/docs/measuring_performance.md) and share more information from us, I'm sure it could be looked into. Feel free to file a new issue if you're able to do that!
