### ISSUE TITLE
Documented way of using hot reloading

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/build#176]
One of the pain points of `build` (but not limited to it, any code generator) is that the edit-refresh cycle is pretty painful (i.e. print debugging for the most part). It would be really sweet to have a way to use hot reloading here. I'm imagining the following API:

```bash
tool/build.dart --hot
```

What I'd like to see:

- [ ] Hot reloading is supported if the generator changes
- [ ] If the generator changes, terminal prints the diff of generated files as they are overwritten

**Comment by natebosch** [comment]
Very cool idea. Even starting with the diff would be nice.

**Comment by matanlurey** [comment]
Is there a good text diffing library somewhere on pub @natebosch?

I could try to help port something, I've needed this for other tests as well.

**Comment by natebosch** [comment]
I haven't come across a diff library in Dart - there is a package called `diff` but I haven't used it.

We might start by adding an option to rename instead of delete somewhere around here:
https://github.com/dart-lang/build/blob/b52ff31dfe9bdbca4843a050ff46993a42ba2061/build_runner/lib/src/generate/build_impl.dart#L314

Currently we delete old assets that should be built. If we rename it instead to <old name>.old we could make it easier to diff against the previous version outside of the build script. I'm not sure if that would have other side effects though.

Maybe instead of adding new functionality to build_runner we should consider making it easier to run a builder against a single input in a testing scenario?

**Comment by matanlurey** [comment]
I imagine this could be done today with spys, but let's punt on this for now.
