### ISSUE TITLE
Origin of long build times are hard to find

### ISSUE THREAD

**Issue by passsy** [dart-lang/build#1777]
```
> time pub run build_runner build
[INFO] Generating build script...
[INFO] Generating build script completed, took 509ms

[INFO] Initializing inputs
[INFO] Reading cached asset graph...
[INFO] Reading cached asset graph completed, took 107ms

[INFO] Checking for updates since last build...
[INFO] Checking for updates since last build completed, took 383ms

[INFO] Running build...
[INFO] Running build completed, took 13ms

[INFO] Caching finalized dependency graph...
[INFO] Caching finalized dependency graph completed, took 51ms

[INFO] Succeeded after 76ms with 0 outputs (0 actions)

pub run build_runner build  10.88s user 1.03s system 141% cpu 8.428 total
```

I noticed a long gap after `Generating build script completed` and before `Initializing inputs` of multiple seconds and started measuring. It turned out that only `~1s` of the overall `~11s` build time is detailed logged. That just 10%. 

I'd like to report performance problems since the build itself takes a few milliseconds and the rest could be cached but it's very hard to find the origin of the longest tasks.

Here's a link to the project: [`passsy/git-revision`](https://github.com/passsy/git-revision)
- Dart VM version: 2.0.0 (Fri Aug 3 10:53:23 2018 +0200) on "macos_x64"
- `build_runner: '^0.9.0'`
- on Mac OS X 10.13.6 17G65

**Comment by natebosch** [comment]
The long time in between logs is caused by the Dart 2 VM parsing sources for the generated build script. Unfortunately there isn't much we can do about that here. In the long term we hope to implement a daemon mode so that only the first startup is this slow then we have a longer living process in the background which can respond quicker. We have not started on that work but you can track progress here: https://github.com/dart-lang/build/issues/1656

**Comment by matanlurey** [comment]
Another good point is using `build` should be quite rare!

Use `watch` (or `serve`) and you won't pay that startup cost over and over again.
