### ISSUE TITLE
How do I build a dart package without main or test?

### ISSUE THREAD

**Issue by ranveerql** [dart-lang/build#1883]
I am trying to find a way to compile a vanilla dart project which does not have any main/test.
Something like bazel build <XXX_library>

I am trying to run pub run build_runner build 
But it does not do anything. Is there a base compiler I can use that can do the job for me?

**Comment by natebosch** [comment]
What do you expect the output to be with no `main`? Who would consume the output and what would they do with it?

**Comment by ranveerkunal** [comment]
The library is used by flutter and angular dart, so when it is used there is a main.
But I still want to have simple way to build this code and throw errors if it is broken. I can fine with say using ddc to compile it to js. Something like bazel build go_library

**Comment by jakemac53** [comment]
In bazel and build_runner building a library on its own does not actually build anything (in bazel it might perform analysis, but not in build_runner). It is the application entrypoints (files with a `main`) which actually cause something to be built, and it will only build the things which are depended on by those applications. This is because what "building" a library means is different for each platform, as well as reducing unnecessary work.

If what you want is static errors, you should rely on the analyzer for that `dartanalyzer .`. This should give you the same errors as compiling with kernel or ddc would give you (in practice that isn't quite true, but that is due to different bugs or missing features in the implementations of the spec across the cfe/analyzer, and are generally weird corner cases of the language).

**Comment by natebosch** [comment]
Closing since we don't have any planned actions here. If you're looking for static errors you can use the `dartanalyzer` tool. If you need those errors to come from CFE you can add at least one VM test that imports the code and use `build_vm_compilers` to run them through CFE to get VM flavored kernel.
