### ISSUE TITLE
Make it possible to override the `.dart_tool/generated` directory

### ISSUE THREAD

**Issue by natebosch** [dart-lang/build#1972]
This could make it possible to create and snapshot a tool that does a specific build which doesn't depend on packages in the pub solve and run it so it doesn't step on the toes of another build.

**Comment by jakemac53** [comment]
I started looking at this, today this is a constant which is referenced in a few locations although not an insane number.

The obvious easy solution is to simply make that a mutable global variable... feels dirty but definitely the easiest approach. It also allows users to simply hardcode this in their custom build script instead of using a command line arg, which actually more directly solves this use case.

We could make it a public method you have to go through to set it, (overrideGeneratedDir?) or we could just remove the `const` from the field.

We can do custom validation logic if we want either way... possibly enforcing it can only be set once or something, maybe even enforce you do it before creating a `BuildRunner` instance? 

wdyt @natebosch

**Comment by jakemac53** [comment]
The alternative is basically plumbing this through `BuildOptions` and down through anything that wants access to this constant (and migrate the constant to a method that takes an optional arg).

**Comment by natebosch** [comment]
I have a slight preference for adding it to `BuildOptions`, but if it's going to cascade into a huge change I'd be fine with a top-level `overrideGeneratedDir` method.

**Comment by jakemac53** [comment]
This is resolved now
