### ISSUE TITLE
over-zealous globbing of valid inputs at start of each build

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/build#200]
It looks like we are globbing all potential inputs ahead of time, including hidden directories etc for the root package, https://github.com/dart-lang/build/blob/1a51edff2c8dff6cff2fe0c25dda39c79ded47c7/build_runner/lib/src/generate/build_impl.dart#L469.

We should be able to skip this step entirely, and just check if inputs are valid lazily when they are requested? We would need to make sure they haven't been created since the current build started, but that should be pretty trivial.

Primary inputs could be collected lazily as well, when the phase that needs them begins.

I might be missing something else though :).

**Comment by natebosch** [comment]
We should be avoiding `['build', 'package', '.pub']` because of [this](https://github.com/dart-lang/build/blob/46e500c48209add989aed7a9ddd8626f3cc98e7f/build_runner/lib/src/asset/file_based.dart#L23) and now `.dart_tool` because of [this](https://github.com/dart-lang/build/blob/46e500c48209add989aed7a9ddd8626f3cc98e7f/build_runner/lib/src/generate/build_impl.dart#L387)

Filed https://github.com/dart-lang/build/issues/374 to make those consistent.

Since we've move towards an eagerly built static asset graph rather than lazy I'll close this out.
