### ISSUE TITLE
'GlobAssetNode' is not a subtype of type 'GeneratedAssetNode' exception

### ISSUE THREAD

**Issue by pschiffmann** [dart-lang/build#2017]
Using the AggregateBuilder from [the docs](https://github.com/dart-lang/build/blob/master/docs/writing_an_aggregate_builder.md) in a package that also uses Angular builders results in this error and stack trace:

```
[SEVERE] Build:
Unhandled build failure!
type 'GlobAssetNode' is not a subtype of type 'GeneratedAssetNode' in type cast
package:build_runner_core/src/generate/build_impl.dart 656:42           _SingleBuild._cleanUpStaleOutputs.<fn>
dart:async                                                              Future.wait
package:build_runner_core/src/generate/build_impl.dart 655:18           _SingleBuild._cleanUpStaleOutputs
package:build_runner_core/src/generate/build_impl.dart 536:11           _SingleBuild._runPostProcessBuilderForAnchor
package:build_runner_core/src/generate/build_impl.dart 509:9            _SingleBuild._runPostProcessAction.<fn>
dart:async                                                              Future.wait
package:build_runner_core/src/generate/build_impl.dart 508:36           _SingleBuild._runPostProcessAction
package:build_runner_core/src/generate/build_impl.dart 488:26           _SingleBuild._runPostProcessPhase.<fn>
dart:async                                                              Future.wait
package:build_runner_core/src/generate/build_impl.dart 487:36           _SingleBuild._runPostProcessPhase
dart:async                                                              _AsyncAwaitCompleter.start
package:build_runner_core/src/generate/build_impl.dart 484:49           _SingleBuild._runPostProcessPhase
package:build_runner_core/src/generate/build_impl.dart 311:20           _SingleBuild._runPhases.<fn>.<fn>
dart:async                                                              _AsyncAwaitCompleter.start
package:build_runner_core/src/generate/build_impl.dart 305:70           _SingleBuild._runPhases.<fn>.<fn>
package:build_runner_core/src/generate/performance_tracker.dart 187:15  _NoOpBuildPerformanceTracker.trackBuildPhase
package:build_runner_core/src/generate/build_impl.dart 305:47           _SingleBuild._runPhases.<fn>
dart:async                                                              _completeOnAsyncReturn
package:build_runner_core/src/generate/build_impl.dart                  _SingleBuild._runBuilder
```

I'm using `Dart VM version: 2.1.0 (Tue Nov 13 18:22:02 2018 +0100) on "windows_x64"`, and I have uploaded an example in [this repository](https://github.com/pschiffmann/build_glob_bug). The contents of that repo are just the result of running `stagehand web-angular` , copy/pasting the `AggregateBuilder`, and adding a `build.yaml`.
To reproduce, run `pub run build_runner build --verbose`.

**Comment by kevmoo** [comment]
Could you include you dart sdk version and the contents of pubspec.lock?

**Comment by pschiffmann** [comment]
> Could you include you dart sdk version

`Dart VM version: 2.1.0 (Tue Nov 13 18:22:02 2018 +0100) on "windows_x64"`

> and the contents of pubspec.lock?

It's included in the repository: https://github.com/pschiffmann/build_glob_bug/blob/master/pubspec.lock

**Comment by jakemac53** [comment]
I did look at this for a bit, but was struggling to repro it in a regression test. I will assign myself though.

**Comment by pschiffmann** [comment]
Did the error not occur when you were using my repo, or could you not write an automated test case? Is there anything I can help you with at this point?

**Comment by jakemac53** [comment]
I didn't try your repro yet - I was just trying to write an isolated test case.

**Comment by jakemac53** [comment]
Either way would be fine, skipping anything that isn't a `GeneratedAssetNode` would probably result in the least code duplication, but changing the method signature to take an `Iterable<GeneratedAssetNode>` feels the most "correct". I don't have a strong opinion.

**Comment by pschiffmann** [comment]
I looked into this today. I think I have a better understanding now what happens in this code, but just to make sure...
What I think I have understood so far:
 * `_SingleBuild._cleanUpStaleOutputs` deletes files from the build output directory that were created there during a previous build.
 * `GlobAssetNode` is a synthetic node that is instantiated when I call `BuildStep.findAssets()`. The node is needed to recognize when matched assets change, so the build system knows it needs to execute the builder again.
 * The `GlobAssetNode` does not represent a file on disk, so it never needs to be deleted from the build output directory.

What I don't understand yet:
 * What is a `PostProcessAnchorNode`? Are it's `outputs` supposed to contain `GlobAssetNode`s?
 * `_cleanUpStaleOutputs()` is also called from `_runForInput()` with the result of a call to `expectedOutputs()`. I suppose that method doesn't return `GlobAssetNode`s, because globs aren't outputs?

Also, if I should look into writing an automated test case, are there any test cases I can use as a foundation, to see how I can create mock data and services to initialize `BuildImpl`?

**Comment by jakemac53** [comment]
> * `_SingleBuild._cleanUpStaleOutputs` deletes files from the build output directory that were created there during a previous build.

Correct, it deletes the previous files that were output by the build step it is about to run.

> * `GlobAssetNode` is a synthetic node that is instantiated when I call `BuildStep.findAssets()`. The node is needed to recognize when matched assets change, so the build system knows it needs to execute the builder again.

Yep, its how we track glob results.

> * The `GlobAssetNode` does not represent a file on disk, so it never needs to be deleted from the build output directory.

Again correct, it is serialized as a part of the asset graph - so in a way it ends up on disk but not as its own file :).

> * What is a `PostProcessAnchorNode`? Are it's `outputs` supposed to contain `GlobAssetNode`s?

These are also special nodes, sort of like `GlobAssetNode`. I can't remember exactly why we needed the special node for it off the top of my head though. But in any case, there is one per primary input to a PostProcessBuilder.

As far as I know, they should not ever have a `GlobAssetNode` as an output. If they do - then that is probably the real bug here. I think this code has an assumption built in where that is never the case.

> Also, if I should look into writing an automated test case, are there any test cases I can use as a foundation, to see how I can create mock data and services to initialize `BuildImpl`?

You can check the [build_test.dart](https://github.com/dart-lang/build/blob/master/build_runner_core/test/generate/build_test.dart) file for examples (and that is probably where the test should live also).

**Comment by kevmoo** [comment]
I just hit this, too!

**Comment by natebosch** [comment]
I think I understand what is happening here. We are tracking unreadable stuff, like `PostProcessAnchorNode`s as potential inputs to a glob here: https://github.com/dart-lang/build/blob/d65ffa52a7b28dbdc2a4188d5bbd519634847daa/build_runner_core/lib/src/generate/build_impl.dart#L688-L695

I can't recall if there was a reason that even unreadable stuff was tracked in `inputs` separately from `results` - an invalidation of a `GeneratedAssetNode` from a later phase than a glob, and certainly a `PostProcessAnchorNode`, should never invalidate at `GlobAssetNode`. I do think we need to track non-output, but otherwise potentially readable nodes for dependencies.
