### ISSUE TITLE
Build programmatically rather than based on InputSet files

### ISSUE THREAD

**Issue by jimmyff** [dart-lang/build#205]
I would like to generate numerous classes programmatically, after looking through the docs I don't believe this is current possible as I have to provide an InputSet which represents a set of files.

In my case I have a Map that contains the specification for the classes I want to generate, I would like to provide this to my phase & builder instead of an InputSet.

**Comment by natebosch** [comment]
It's not possible to use anything other than the input filenames to determine outputs. I've started documenting the reasons for this [here](https://github.com/dart-lang/build/wiki/Writing-a-Builder#output-restrictions)

If you are generating multiple Dart classes you can put them in the same library file. If the set of outputs are relatively stable you could try creating files  that indicate where they will be - if you know you'll want `foo.dart` and `bar.dart` you could create `foo.yaml` and `bar.yaml` where those files have the information needed to create the outputs.

**Comment by jakemac53** [comment]
I would recommend putting this map into a serializable format (json, yaml, protobuf, etc), then putting that in a file on disk and using that file as your input, and deserializing it during your build.

If you have it as a part of your actual build script, then any time you update it that will invalidate your entire build instead of just the things that relied on that configuration.
