### ISSUE TITLE
Upgrading to 0.9.4+1 and accessing element.unit in generateForAnnotatedElement produces an error

### ISSUE THREAD

**Issue by twistedinferno** [dart-lang/build#2071]
build: 1.1.1
  source_gen: 0.9.4+1
  build_runner: 1.2.8
  Linux

I have been retrieving my code lines with the following line
`var childElements = element.unit.childEntities.map((x) => x.toString()).toList();`

This would retrieve each line of code in the file.

I've updated to source_gen version `0.9.4+1` and now, whenever `element.unit` is accessed inside my generator file, I get the following error.  Is there a replacement for element.unit?  It now seems to be deprecated and errors.  I asked this question on the source_gen repo but I think it might be more relevant here.

```
Error running TypedefForFnGenerator
NoSuchMethodError: Class 'RestrictedAnalysisContext' has no instance method 'resolveCompilationUnit' with matching arguments.
Receiver: Instance of 'RestrictedAnalysisContext'
Tried calling: resolveCompilationUnit(Instance of 'FileSource', Instance of 'LibraryElementImpl')
Found: resolveCompilationUnit(Source, LibraryElement) => CompilationUnit
```

This is what I'm trying to do; I'm trying to get the fn_a typedef name from my list of parameters
`List<int> f6(fn_a fn, int a) => fn(5, [1, 2], a);`

`fn_a fn` parameter is a typedef that defines the function type like this
`typedef fn_a = List<int> Function(int, List<int>, int);`

if I use `element.parameters` I can't get the typedef name, this the result I obtain when I use element.parameters, as you can see I don't get the name just the underlying type of the function param
`[(int, List<int>, int) → List<int> fn, int a]`

but with `element.unit.childEntities.map((x) => x.toString())` I was able to get the whole line of the code and 'easily' extract the parameters including the typedef.  As you can see `fn_a` typedef is in the result.
`"@TypedefForFn() List<int> f6(fn_a fn, int a) => fn(5, [1, 2], a);"`

So, I either need a solution for the error above when I use element.unit or I need to find a way to extract the typedef name from my parameters. Any ideas?

**Comment by natebosch** [comment]
> I've updated to source_gen version `0.9.4+1`

you also updated to analyzer `0.35.0` which was the breaking change here

Unfortunately we don't have good changelogs for breaking changes in analyzer which is why things like this fall through the cracks. It doesn't help that we've been conditioned to expect that most analyzer breaking version bumps are "safe" since they haven't impacted codegen users for a while. It doesn't help further that this breaking change was influenced by both the `build_resolvers` package which you don't depend on directly, along with the analyzer and we use the analyzer version as the gate.


What is happening here is that you're getting an `Element` produced through a different code path in the analyzer, which has some different behaviors. Specifically, for this case, `.unit` doesn't work anymore.

I think the new code path you'll want is something along the lines of:

```dart
var resolvedLibrary = await element.session.getResolvedLibraryByElement(element.library);
var declaration = resolvedLibrary.getElementDeclaration(element);
var unit = declaration.resolvedUnit.unit;
```

cc @scheglov - does that look correct to you?

**Comment by twistedinferno** [comment]
Hi @natebosch, thanks for your reply.

Yes that works :-)  I had also managed to get the line information this way 
```
   element.session
       .getParsedLibraryByElement(element.library)
       .units.first.content.toString(),
```

is `getResolvedLibraryByElement` more correct than `getParsedLibraryByElement`?  I'm pragmatic enough just to be happy with either! (unless one might break of course!)

Unfortunately `built_value` doesn't support the latest `analyzer` though so I have a conflict in my packages.  I have this open, I can wait a bit
https://github.com/google/built_value.dart/issues/598

**Comment by natebosch** [comment]
Either `getParseLibraryByElement` or `getResolvedLibraryByElement` should be safe to use. The `Parsed` version may be faster than the `Resolved` version.

I think `built_value` should be updating soon.

Closing this issue since I don't think there are any actions to take from the build side.
