### ISSUE TITLE
Failures when Dart updates

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/build#2075]
_From @drpond1 on November 17, 2018 14:19_

When a new version of  dart appears eventually my code will not run -- some kind of script error on startup, before it gets to my code.  (Unfortunately, I did not save the error.)
    This is resolved by updating the dartsdk, getting/updating dependencies and rebuilding.
It seems to me I should still be able to run with the old system.    If not, there should at least be a  message that a dartsdk update is required. 

 This is the second time this has happened in the last few months.      

I use IntelliJ Community Edition.

_Copied from original issue: dart-lang/sdk#35203_

**Comment by vsmenon** [comment]
_From @alexander-doroshko on March 5, 2019 8:46_

@vsmenon, I'm not sure `area-intellij` is the right label here.
Without error details the issue doesn't seem to be actionable at all, so maybe just close?

**Comment by vsmenon** [comment]
_From @drpond1 on March 5, 2019 20:38_

I believe this was addressed in a recent related issue.   The problem is
that while I am working on a project,   there can be an update from Dart
which when a build happens causes builds to fail.     I think this is new
with Dart 2.0  because of the recommended

build_runner: ^0.10.0
build_web_compilers: ^0.4.


My situation is that I may keep an older app running,

because I want to copy "user" data from the old/flawed app into the new one.


New builds may fail if there is a Dart update between the time the older app was

started and the new build was attempted.  (There cannot be another running

app.)

Because of the build failure, new code executes with a missing file error.


***

The failure is intended by the Dart design and the

shown pub spec is still recommended  so the issue was closed.

***


The residual problem is that the failures I encountered are unexpected

 and recognition of how to recover was not immediately obvious to me.


If this analysis of the problem is correct, the simplest fix is a small

change in documentation.

However, my situation might be sufficiently rare that no change should

be made.

**Comment by vsmenon** [comment]
Ahh, my mistake triaging.  I'll move.

**Comment by natebosch** [comment]
> When a new version of dart appears eventually my code will not run

> This is resolved by updating the dartsdk, getting/updating dependencies and rebuilding.

This is very unclear to me - what action did you take that triggered the error? My initial assumption was that the action was updating the Dart sdk, which triggered a build failure - but that wouldn't make sense if updating the SDK is part of the solution steps...

> It seems to me I should still be able to run with the old system.

The only time you should need to update the SDK is if you are using new features only found in the new SDK. If your code, and the versions of dependencies you're using, worked with the old SDK they should continue to work. Upgrading the SDK within major versions also should not trigger build failures except in remote edge cases. Upgrading from Dart 1.x to Dart 2.x is expected to cause failures which require changes in your code.

>  If not, there should at least be a message that a dartsdk update is required.

This leads me to think the issue is instead that you updated some packages and things failed until the SDK was updated? This is expected only if the package maintainers are doing something wrong - for example if they use a new feature from Dart 2.2 but do not indicate the requirement in their pubspec (an unfortunately common mistake, even the Dart team does this from time to time).

> Unfortunately, I did not save the error.

Without a specific error it's very unlikely we'll be able to investigate.

I'm afraid this issue is not actionable for us. If you gave give us a specific reproduction case where updating the Dart SDK within a major version (for example 2.0 to 2.1) causes the build to fail we can investigate. Otherwise if you can give a specific reproduction case where updating a dependency required an update to your locally installed SDK we can help you track down the mistake that was made.

**Comment by drpond1** [comment]
I cannot tell if you looked at the updated comment or not.  vsmenon posted
it so that it
  appears in the middle of the thread.

If begins:
"I believe this was addressed in a recent related issue. The problem is"

****
Short version:

My situation is that I may keep an older app running, because I want to
copy "user" data from the old/flawed app into the new one.   New builds may
fail if there is an update  to the Dart build packages between the time the
older app was  started and the new build was attempted   Because of the
build failure, new code executes with a missing file error.

****

This is how the build procedure is supposed to work.

  It would be useful to simply be able to fix a small problem without
having to set things back up,  but now that I understand the problem  I can
deal with it.     I suggested an update in the documentation OR that the
issue just be closed.
