### ISSUE TITLE
Further info on older build problem

### ISSUE THREAD

**Issue by drpond1** [dart-lang/build#2101]
In a previous issue that has been closed, I encountered a problem running my app after a dart update.    This message clarifies one of the issues.

What I typically did in the past was do a build and then run the code from IntelliJ.  One
common  "problem"  was that the code does not run because it could not find the server.
However,  the "problem"  is because the build says process completed with no errors in the 
messages pane,   but this does not mean everything is done.   The dart server is still being updated/rebuilt   This takes some time to complete.  More than a minute on my system.  
(Chrome says something like the page is not responding,)

Know I now to check the Dart Dev server messages before running again.

Perhaps,  some message about the Dart Dev server possibly being rebuilt (see
Dart Dev server pane).     should appear in the messages panel after the  "build" process
is  complete,     ???

**Comment by natebosch** [comment]
> What I typically did in the past was do a build and then run the code from IntelliJ

What do you mean by "run" here? You mention chrome later so I assume this is a web app? Are you launching chrome from IntelliJ?

> The dart server is still being updated/rebuilt

I don't know what this means.

> Chrome says something like the page is not responding

When you run `pub run build_runner serve` or `webdev serve` the server will always respond after the build is done.

How can we reproduce what you are seeing? Can you give screenshots of what you are seeing and what you expect to see instead?

This issue is not actionable for us as is.

**Comment by natebosch** [comment]
I think https://github.com/dart-lang/build/issues/2075 was the referenced previous issue. It also did not contain enough information for us to understand or reproduce the issue.

**Comment by drpond1** [comment]
I go to the pubspec.yaml page and say update dependencies, and then build.   I wait until the message in the messages pane says the process is done.   I go to my web page in IntelliJ and click on the chrome Icon.   In the chrome browser tab for the web page, it says it does not load 

The "issue"  is very simple.  the messages pane seems to suggest that the page is ready to run.
  At least that is what I thought when it said the build process was finished with no errors.
  That is not  necessarily the case because the web dev server might  still be rebuilding.
   One can see the messages for that on the web dev server pane.  But I did not know that I needed to
   check there as well.
   I normally would expect some message in the messages pane saying that things were ready to run.     
    
   ...
    As for issue 2075.
    
     Now that I understand how to solve the problem above, 
       I think I have a found a workaround for the problem I described in 2075.   

       An attempt to run my  revised code might cause a rebuild and  the webdev server may be halted.    
      The fix is to just  start the server back up.  

        The problem is detected when you run the web app and see that the server isn't working.
         Kill the page,  To start the server,  run the web app again and then
        go to the web dev server pane and wait for the
        messsage saying the server has started,   Now run the web app again.   And it works.

**Comment by natebosch** [comment]
>and then build

Build and Serve are different concepts in `build_runner` and `webdev`. It's unsurprising that starting up a _fresh_ serve process might take a few seconds, regardless of whether a build was already done. The server is started independently of when the build _within_ that serve process is done, but the server doesn't start listening instantly when you start a serve process. There is some overhead of startup.

> the messages pane seems to suggest that the page is ready to run

If you're running a build and it's finished, it means that the code has been compiled, not that there is a listening server on some port.

> That is not necessarily the case because the web dev server might still be rebuilding.

Whether the server is listening on a port is orthogonal to "rebuilding". The _startup_ time in a fresh serve process is separate form the _build_ time. The server won't _respond_ to request until the build is done (which should be fast if there was a previous build that completed), but it will be _listening_ for requests as soon as it's started, and the browser won't complain. You're probably seeing that it takes a few seconds to start listening. Once `webdev` is using snapshots the startup time will hopefully be improved, but will never be instant regardless of having run a previous build.

> An attempt to run my  revised code might cause a rebuild and  the webdev server may be halted.    
  The fix is to just  start the server back up.  

A serve process is long living and does not need to be restarted to reflect changes in your code. I don't know what IntelliJ might be doing here, but we of course can't serve pages to the browser without a running process.

> Kill the page,  To start the server,  run the web app again and then go to the web dev server pane and wait for the messsage saying the server has started,   Now run the web app again.   And it works.

Right, if there is no server running then the page can't be loaded. You need to have a server running.


This all looks like some confusion about "build" vs "serve". Hopefully I've cleared that up. The only time you'll be able to load a page in your browser from the dev server is if the dev server is running. The dev server will only be running during a "serve" process, not a "build" process. The startup time for a "serve" process is independent of whether you have previously run a "build".

**Comment by drpond1** [comment]
This is my summary:

The problems started to occur after the new way build/serve was working in
Dart 2.0.
This might be because there are unexpected "builds" happening because of
the extra
    dependencies in pubspec.yaml that are not part of my code base.
 When this is combined with trying to keep older versions of web pages
running in the browser the web dev server may be halted, and so a new "run"
of the app may fail.
In such a case, just restart the web dev server (for example, by trying to
run the app).    For IntelliJ,  you can look at the web dev server pane to
determine when it has restarted.

**Comment by natebosch** [comment]
> This might be because there are unexpected "builds" happening because of the extra dependencies in pubspec.yaml that are not part of my code base.

The extra dependencies to not cause _new_ builds to happen. They shift the responsibility for performing a build from `pub build` to `pub run build_runner build`, but do not incur any overhead in terms of additional code being compiled or cause builds to be more frequent.

Shipping the build system as a dependency rather than in `pub` was a way we could move faster with the build system than the SDK since we can release more often.

> When this is combined with trying to keep older versions of web pages running in the browser the web dev server may be halted, and so a new "run" of the app may fail.

Nothing the browser does can cause the dev server to be "halted". Nothing about a page "running" in the browser has any impact outside of that browser.

If you're trying to switch between multiple versions of your app or the Dart SDK and spinning up separate servers they might be competing for ports? Only a single server can run on a given port. You might try choosing a different port for one or the other so that they can both be running at the same time.

**Comment by drpond1** [comment]
ok.  
  It is possible that because new releases are happening more frequently,  I am more likely to make the mistake of testing the system out with an explicit build at the wrong time.

For me,  this is no longer an issue because I have a better understanding of what is happening 
  and a relatively quick and easy fix if my problem occurs again.   I tested the approach and was happy with the result.

 Thank you for your help.
