### ISSUE TITLE
Meta: Can build_runner support running other pkg's builders?

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/build#216]
i.e., If you ever wanted `build` to be a ~100% replacement for `barback`, we'd need this.

This would also make `build_runner` a slightly viable alternative to `bazel_codegen` - as you wouldn't be required to check in the results of code generation (just like bazel). Anyway, just an open question - maybe it's not even possible.

**Comment by jakemac53** [comment]
This is possible but it becomes less straightforward to run your app, as the default `.packages` file (created by pub) won't work. We need to use a different copy of the packages with the codegen added.

The most straightforward way to do this is probably by creating a special folder where all build output is written to, and then you have to run your app from that folder instead of your root package folder. We can create a special `.packages` file in there that points at a special package cache. This should be able work as a general solution for all types of apps, but has the downside of adding some extra confusion. If you want to debug you have to set breakpoints on files in the generated folder, and editing those files accidentally will not actually edit your app (and your changes could get bashed over at any time by a build).

Alternatively, for web apps specifically we can force people to use the [serve](https://www.dartdocs.org/documentation/build_runner/0.3.0/build_runner/serve.html) command (similar to pub serve), which would serve files from a special package cache.

For vm apps we could create a `run` command probably which runs your app as a sub-process with a special `.packages` file (assuming this functionality exists). Alternatively the build package could emit a `build.packages` file or something which people can pass explicitly when they run their app.

**Comment by matanlurey** [comment]
Sgtm. Is it worth adding this as a longer-term FR?

And is it worth supporting this for VM (server-side/CLI) applications too?

**Comment by natebosch** [comment]
Yes let's keep this open as a FR.
