### ISSUE TITLE
Fields on ElementAccessor

### ISSUE THREAD

**Issue by twistedinferno** [dart-lang/build#2183]
Dart 2.2.0
Build 1.1.1

I have an ElementAccessor object returned from the generateForAnnotatedElement element.  I wondered if it was possible to get a list of properties for that object.
```
class ValueTGenerator extends GeneratorForAnnotation<ValueT> {
  FutureOr<String> generateForAnnotatedElement(
      Element element, ConstantReader annotation, BuildStep buildStep) async {
```
For instance I have an annotated Company class which contains a Person field.  
```
@ValueT()
class Company {
  Person person;
}
```
I can access the Person field (ElementAccessor) but I can't seem to get it's fields.  Is there a way to do this?  (I can send some more code if that would help)

**Comment by natebosch** [comment]
Do you mean `PropertyAccessorElement`? It has a [`returnType` field](https://pub.dartlang.org/documentation/analyzer/0.35.2/dart_element_element/FunctionTypedElement/returnType.html) which is a [`DartType`](https://pub.dartlang.org/documentation/analyzer/0.35.2/dart_element_type/DartType-class.html). From there I _think_ you can use [`element`](https://pub.dartlang.org/documentation/analyzer/0.35.2/dart_element_type/DartType/element.html) to get to the class definition. You'll hopefully be able to cast it to a `ClassElement` and read it's [`fields`](https://pub.dartlang.org/documentation/analyzer/0.35.2/dart_element_element/ClassElement/fields.html)

Closing for now since I think this should work for you. If it doesn't add a comment and we can reopen.
