### ISSUE TITLE
input files are deleted

### ISSUE THREAD

**Issue by zoechi** [dart-lang/build#219]
I generated model classes (`lib/models/xxx.dart`) using a `PhaseGroup` `Action`
and then applied the `built_value` `Action` to generate serialization for these models.

I then removed the `PhaseGroup` that generates the model classes to leave the `built_value` `Acton` active.
But running `build.dart` deleted all generated model classes.

```
  final phases = new PhaseGroup()
//    ..addPhase(new Phase()
//
//      // Generates the `lib/models/xxx.dart` dart classes
//      ..addAction(new ModelBuilder(api.version),
//          new InputSet('mypackage', ['temp/models/*.json'])))
    ..addPhase(new Phase()
      ..addAction(
          new GeneratorBuilder([new BuiltValueGenerator()]),
          new InputSet(
              'mypackage',
              api.models.keys
                  .map((name) =>
                      'lib/src/models/${new ReCase(name).snakeCase}.dart')
                  .toList()
                    ..add(
                        'lib/src/models/serializers.dart')))); 

  await build(phases, deleteFilesByDefault: true);
```
The build_runner seems to determine what classes were generated from its cache rather then from the `PhaseGroup` configuration.

**Comment by jakemac53** [comment]
So any time the build script itself changes (or any transitively reachable file), it deletes all previous outputs and re-runs from scratch. This is by design as its really the only sane thing to do.

Similarly if you delete the input file which created some output it will delete the corresponding output, this is so that it keeps your working directory clean.

If you really want just a one time build, you could create a different build script which contains just the first phase that you commented out, and then either leave it in to be manually ran later or delete it afterwords? In general though you shouldn't need to do this, builds are incremental and those models would only be recreated if the inputs changed or the build script changed.

**Comment by zoechi** [comment]
Thanks. With this info I should be able to find a strategy.
