### ISSUE TITLE
How to run language experiments with WebStorm? 

### ISSUE THREAD

**Issue by mnordine** [dart-lang/build#2229]
<img width="500" alt="Screen Shot 2019-04-14 at 6 42 47 PM" src="https://user-images.githubusercontent.com/1924573/56129730-43754e00-5f59-11e9-9ef1-63c89cf3bb82.png">

How do you pass in flags to enable language experiments?

**Comment by natebosch** [comment]
> How does the Dart team test new language features with DDC and dart2js?

Within the SDK we don't typically run through `build_runner` or `webdev` - we use much more static and manually configured builds.

We have avoided something like `ddc_args` because such an option would _need_ to be global, but we don't have a nice way to enforcing that and the UX when you get it wrong is terrible.

How badly is this needed?

**Comment by mnordine** [comment]
> Within the SDK we don't typically run through build_runner or webdev

Are you guaranteed when testing language features on these manually configured builds, issues won't show up in ddc or dart2js?

**Comment by natebosch** [comment]
> Are you guaranteed when testing

No test can offer a 100% guarantee. We also run tests in the build system repo against bleeding edge SDKs to catch issues quickly.

**Comment by jakemac53** [comment]
We do support `--enable-experiment` as a bulid_runner flag now, and builders can read that configuration. The web builders do read it, and the analyzer will be configured with them.
