### ISSUE TITLE
App crashes due to client.js (build_web_compilers 2.0.0)

### ISSUE THREAD

**Issue by cooler-king** [dart-lang/build#2269]
An app builds and runs but crashes due to `$dartRunMain` being undefined in `client.js`

Dart 2.3.0
build_web_compilers 2.0.0
Windows x64
Chrome

Same thing happens in another app.
Backing off to build_web_compilers 1.2.1 the issue goes away and the app runs without crashing.

![image](https://user-images.githubusercontent.com/11008367/57638381-acada880-757b-11e9-9ddc-d37b9af1e9f1.png)

**Comment by jakemac53** [comment]
weird, can you repro this consistently?

**Comment by cooler-king** [comment]
Happens every time

**Comment by jakemac53** [comment]
@cooler-king getting around to taking a look at this now - can you set a breakpoint at that line (10588) and check that `self` is window? If that is somehow not window then that would be the likely culprit here.

**Comment by jakemac53** [comment]
Another thing you could try, is in the `*.dart.bootstrap.js` file for your app, look for a line that looks something like this:

```
window.$dartRunMain = <something>
```

You can check what that `<something>` is and whether it is defined. Maybe we are trying to reference something by the wrong name there.

**Comment by cooler-king** [comment]
self is window but `$dartRunMain` is undefined.  Trying the second suggestion now.

![image](https://user-images.githubusercontent.com/11008367/58114640-2ff77b80-7bc6-11e9-94eb-61d18d90fe03.png)

**Comment by cooler-king** [comment]
Hmmm.  I'm not sure what it's supposed to be doing, but it looks it's trying to run the wrong (and non-existent) main.

![image](https://user-images.githubusercontent.com/11008367/58115095-54a02300-7bc7-11e9-9dac-1087f249db15.png)

This is an app that lives in in `example` and is served by `webdev serve example:9342 hostname=0.0.0.0`.
main runs Gallery and Gallery contains example_arcs (and the others).

![image](https://user-images.githubusercontent.com/11008367/58115344-dd1ec380-7bc7-11e9-945c-a4f1732a3f82.png)

**Comment by jakemac53** [comment]
If you look at the `app` object, does it have an `arcs__example_arcs` object with a `main` function?

**Comment by cooler-king** [comment]
No.  You can see what it has in the screenshot.  That's the whole thing.

**Comment by jakemac53** [comment]
Oh right I didn't see that on the right :). It looks like what it wants in this case is `app.main.main` which doesn't make sense, ill do a bit more investigation on my end.

**Comment by jakemac53** [comment]
Oh interesting - it looks like you are actually serving the `index.html` file but we are bootstrapping it as if it was the `example/arcs/example_arcs.dart` file.

My best guess here is that this is because you have a dependency cycle between the `main.dart` and the `arcs/example_arcs.dart` files, which is confusing our module name logic, which is based on the JS path and not the primary input id to the bootstrap action. It is a bit hard to explain but I am pretty sure that is the case.

A bit hard to explain, but one possible workaround you can try for now is renaming your `main.dart` file such that it is the alphabetically first file in your web directory (a.dart or something), that should make the js module name match up and things might magically start working.

I will try and create a repro case on my end to verify this behavior as well.

**Comment by jakemac53** [comment]
Confirmed the issue and I have a bug fix pending, thanks for the report!

**Comment by cooler-king** [comment]
#2274 is really dogging me, if you can do something about that one.

**Comment by jakemac53** [comment]
For that one I don't think there is really anything to do on our end.  It appears it is specific to certain machines which get in a corrupted state somehow and a reboot is the only fix?

**Comment by jakemac53** [comment]
Fix has been published in build_web_compilers version 2.0.1, please follow up if that doesn't solve the issue :smile:
