### ISSUE TITLE
Need support for building React

### ISSUE THREAD

**Issue by Meai1** [dart-lang/build#2323]
I really cant stress strongly enough that we need custom compilation support back in the build system. (inplace transformers) Dart cannot compete against the mass innovation on the javascript side if output cant be modified after initial compilation. They write new compilers every day that make their job easier. Svelte for example is the latest addition. In short: Creating React in Dart is not possible. Isnt that a killer argument? Surely we have to at least give the community the tools to make React possible in Dart. This requires in place transformers.

**Comment by natebosch** [comment]
The build system is modeled after https://bazel.build/ which does not support in place transformations and that isn't a decision we're going to change.

https://github.com/dart-lang/build/blob/master/docs/transforming_code.md#but-why has some documentation on how to live within these limitations. If you have specific questions on something that is blocking you we can try to help. As is this issue is not actionable.
