### ISSUE TITLE
Allow reading assets that were written in the same build step

### ISSUE THREAD

**Issue by simolus3** [dart-lang/build#2479]
At the moment, the build runner forbids builders to read an asset that has been written in the same build phase:
```dart
await buildStep.writeAsString(tempAssetId, 'void main() {}');
await buildStep.readAsString(tempAssetId); // throws
```

This restriction can be loosened, so that builders are able to read (and resolve!) assets that were written in the same `BuildStep`. See https://github.com/dart-lang/build/issues/2431#issuecomment-537203396 and the following replies for further discussion.

**Comment by simolus3** [comment]
@jakemac53 Can we unambiguously identify a (non post-processing) build step by its phase and primary input?

**Comment by jakemac53** [comment]
Yes

**Comment by jakemac53** [comment]
Also as a pointer towards the right direction you probably want to look at SingleStepReader https://github.com/dart-lang/build/blob/master/build_runner_core/lib/src/asset/reader.dart#L36

**Comment by jakemac53** [comment]
You might also want to give that access to the AssetWriterSpy https://github.com/dart-lang/build/blob/master/build_runner_core/lib/src/generate/build_impl.dart#L465 which tracks what assets have been written by the build step so far

**Comment by simolus3** [comment]
Thanks! I managed to get the example from the issue description working.

> Also the resolver would have to be re-initialized, we would need some special logic here.

I have a general idea on how to approach this, but I would appreciate some quick feedback before I start working on it. Can we make the `BuildAssetUriResolver` call `driver.changeFile` for updates before the build step finishes? If we just call `performResolve(step, [newlyWrittenAsset], driver)` after each write, would that have a significant performance impact? I assume that most directives appear in `_cachedAssetDependencies` already, which would make the crawl fairly minimal.

I could also imagine keeping an internal list of written assets in the `PerActionResolver` and then only call `performResolve` if any of these assets is resolved by the builder. That would likely eliminate any performance impact for existing builders that don't read their own inputs.

If I follow that approach, what would be the best way inform resolvers on newly written assets? Add another method to the `Resolver` interface? Pass a `Stream<AssetId>` to `Resolvers.get`?

**Comment by natebosch** [comment]
> If we just call `performResolve(step, [newlyWrittenAsset], driver)` after each write, would that have a significant performance impact?

Most likely yes, I'd expect this to negatively impact performance. We should make this as lazy as possibly and only perform the resolve if the builder requests the result.

> what would be the best way inform resolvers on newly written assets? Add another method to the `Resolver` interface?

I wouldn't want to do this. The builder shouldn't see any of this.

> Pass a `Stream<AssetId>` to `Resolvers.get?`

Maybe? It won't be easy to roll this out since it's a breaking change on `Resolvers`. Shouldn't impact builder authors but it will take an extra few steps adjusting the build systems to this interface.

I think the more likely approach would be something along the lines of:

- Hold a `BuildStep` reference on `PerActionResolver`. It already has the same lifetime.
- Change the `_delegate` field from `ReleasableResolver` to the specific `AnalyzerResolver` class.
- When calling an API like `libraryFor`, if we don't already have it resolved we could maybe reach down into the `BuildAssetUriResolver` instance on the underlying `AnalyzerResolver` and do a lazy `performResolve` at that point.

I haven't thought deeply about this so I'm not sure if this would all end up being the right thing to do, but it's the first approach I'd investigate.

**Comment by simolus3** [comment]
> When calling an API like `libraryFor`, if we don't already have it resolved we could maybe reach down into the `BuildAssetUriResolver` instance on the underlying `AnalyzerResolver` and do a lazy `performResolve` at that point.

That works, thanks! It looks like this would solve #493 as well. 

I'll write more tests tomorrow and then open a PR.
