### ISSUE TITLE
build_runner: Dart SDK 2.6.0-dev.8.0 - Flutter Dart SDK 2.5.0

### ISSUE THREAD

**Issue by huextrat** [dart-lang/build#2515]
Hi,

Since the version 1.7.2 of `build_runner` and the merge of https://github.com/dart-lang/build/pull/2505, the minimum version of Dart SDK is `2.6.0-dev.8.0`.
It's a bit unfortunate given that Dart's version of Flutter stable channel is `Dart 2.5.0`. 

Why did you make such an important version upgrade in a minor release? This forces Flutter users to have build_runner on version `1.7.1`.

Also the documentation of this version failed on [pub.dev](https://pub.dev/documentation/build_runner/latest/log.txt) indicating the problem of this Dart SDK version upgrade.

**Comment by jakemac53** [comment]
> Why did you make such an important version upgrade in a minor release?

We use semantic versioning - this is considered a bug fix and so we incremented the patch number.

This shouldn't have any meaningful downside in any case - bumping the major or minor version would not change the sdk constraint.

>  This forces Flutter users to have build_runner on version 1.7.1.

You should be able to get it on the master or dev channels soon if you can't already. I don't have insight into flutter release or merging schedules but they stay fairly up to date.

With the Dart sdk you would also have to be on the dev channel to get this.

> Also the documentation of this version failed on [pub.dev](https://pub.dev/documentation/build_runner/latest/log.txt) indicating the problem of this Dart SDK version upgrade.

This is a known problem with the `pub.dev` website. They always run a new-ish (but not even always the latest) stable dart sdk instead of selecting an sdk in the range that each package supports.
