### ISSUE TITLE
How to get sdk sources for debuging in browser?

### ISSUE THREAD

**Issue by svarl** [dart-lang/build#2550]
Tested on 
```
Dart VM version: 2.4.0 (Wed Jun 19 11:53:45 2019 +0200) on "macos_x64"

webdev 2.5.1
build_runner 1.6.4
build_web_compilers 2.4.1
```

1) Run `webdev serve`
2) Open website with dev-tools 

Some *.js.map files not loaded:
```
packages/build_web_compilers/src/dev_compiler/dart_sdk.js.map
packages/build_web_compilers/src/dev_compiler_stack_trace/stack_trace_mapper.dart.js.map
``` 

How properly configure builder to get map files & sdk sources?

**Comment by jakemac53** [comment]
We don't support the sdk source maps because as configured they aren't valid - as in they don't point at valid uris for us to use on the web.

There isn't much _use_ in debugging these files (they would typically be blackboxed by default anyways) and we don't have any current plans to fix it as it is difficult to do without causing other problems such as code bloat in release builds.

**Comment by svarl** [comment]
Thanks for answering
