### ISSUE TITLE
Warn users of older build_web_compilers to update

### ISSUE THREAD

**Issue by nshahan** [dart-lang/build#2564]
@natebosch I'm ready to land the first CL that starts the removal of analyzer based DDC.
https://dart-review.googlesource.com/c/sdk/+/127067

The breaking change notice describes the users that will have problems.
https://github.com/dart-lang/sdk/issues/38994

It would be nice to detect when someone is using an SDK after the latest release (at this time 2.7.0-dev.2.1) and instruct them to bump their dependency to something like:  build_web_compilers: ^2.0.0.

I'll track this issue to help me know when I should consider it safe to land my first breaking change.

**Comment by jakemac53** [comment]
What does `dartdevc` do if you pass the old command line arguments now (not -k but the other ones)?

We could potentially add something in dartdevc to give its own error when we see that message? That would be a little better because it would work for all users without requiring them to get a newer version of build_web_compilers 1.x to see this error.

**Comment by jakemac53** [comment]
Another option is we could simply _require_ the `-k` argument in perpetuity, and give a nice error if it is not provided.

**Comment by nshahan** [comment]
DDC will now ignore `-k` but detects if you pass `ddc_sdk.sum` in any way and recommends bumping the build_web_compilers spec. Feel free to do what you want with this issue now.

**Comment by natebosch** [comment]
I'm not sure the best way to get this removed since I don't think we want to merge the commit back in.

I've got a version that should be ready to publish with a new warning:

https://github.com/dart-lang/build/commit/710d0bafff964b6ab84fcee3ff80d0bbfc8491cd

It is silent when using `dart2js` so that projects can continue to use release builds if that is working for them.

The output when using `dartdevc` looks like:

```
[INFO] Generating build script completed, took 227ms
[SEVERE] build_web_compilers|entrypoint:
Support for dartdevc in build_web_compilers < 2.0.0 has been removed.

Please upgrade your dependency to:

dev_dependencies:
  build_web_compilers: ">=2.0.0"

[SEVERE] build_web_compilers|entrypoint:

Invalid argument (compiler): dartdevc is no longer supported by this version: "dartdevc"
[SEVERE] build_web_compilers|entrypoint:
Failed to instantiate builder for _test with configuration:
{
 "dart2js_args": [
  "--minify"
 ]
}
```

The min SDK version is 2.7.0 even though that technically might still support DDC, because something in `build_web_compilers` seems to be broken on that SDK anyway. Likely related to the analyzer summary 2 work.

I'd like @jakemac53 to sign off on my plan:

- Publish from this branch locally.
- Tag with the version.
- Delete the branch.

We won't see this commit on our `master` branch history at all, but it will still be accessible through the tag. The changelog entry will not be present in any future versions we publish.

**Comment by jakemac53** [comment]
LGTM @natebosch

**Comment by natebosch** [comment]
New commit I'll publish is https://github.com/dart-lang/build/commit/e0c6ff30b8da63f7bb2f9d190c2885e92be6c8ca

The only difference is I lowered the SDK bound to `2.6.0` since that version was also already broken by the analyzer summary2 migration.

**Comment by natebosch** [comment]
Published and tagged. https://github.com/dart-lang/build/tree/build_web_compilers-v1.2.3
