### ISSUE TITLE
Put a package config json file in the scratch space when we compile

### ISSUE THREAD

**Issue by natebosch** [dart-lang/build#2619]
This is how the compilers will determine which libraries are opted in to null safety.

**Comment by jakemac53** [comment]
This branch does it https://github.com/dart-lang/build/tree/package-config-file - I also simplified a lot of the logic around this so there is always one valid package config file and we don't redo a lot of work.

Note that it doesn't work yet since kernel doesn't seem to allow the new format yet, so I won't send out a PR until it works.

**Comment by jakemac53** [comment]
Kernel does now read the file, but I am trying to figure out how to do invalidation here.

Unfortunately I think for now we will have to just throw away the entire build if the package_config.json file changes at all for now.

This is because while we can add the `.dart_tool/package_config.json` file as a source, we can't actually construct an asset id for it from within a builder because we don't expose the package graph to builders (or what the root package name is).

**Comment by jakemac53** [comment]
This is done now
