### ISSUE TITLE
Warn if the analyzers current language version does not match the current sdk version

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/build#2673]
The analyzer doesn't have tight sdk constraints - and may not even support the current language version at all.

We should detect this and warn the user that they should update their analyzer.

See https://github.com/dart-lang/sdk/issues/41583 for context.

**Comment by jakemac53** [comment]
So, one thing I realized when implementing this warning is that I don't know what to do for people who are on an older sdk but a newer analyzer

Upgrading analyzer further obviously won't help those people, and actually the analyzer will end up trying to analyze files with NNBD on when it shouldn't (their sdk doesn't even support it).

Is it reasonable to (or does analyzer already) set the min sdk on analyzer versions to always >= the language version it supports to avoid this?

Or can we add a mechanism to downgrade the default language version to analysis driver?

**Comment by stereotype441** [comment]
@jakemac53 @scheglov 
> So, one thing I realized when implementing this warning is that I don't know what to do for people who are on an older sdk but a newer analyzer
> 
> Upgrading analyzer further obviously won't help those people, and actually the analyzer will end up trying to analyze files with NNBD on when it shouldn't (their sdk doesn't even support it).
> 
> Is it reasonable to (or does analyzer already) set the min sdk on analyzer versions to always >= the language version it supports to avoid this?

I think this would run into problems when we publish interim releases of the analyzer that are between major releases of Dart.  For example, right now the master branch of the Dart SDK is at 2.9.0-edge.<sha>, whereas the latest stable release is 2.7.2.  There are developers using Dart 2.7.2 who need the latest analyzer API (because they are using a code generator package that depends on it), so we have to ensure that versions of the analyzer we publish now have a minimum SDK constraint no higher than 2.7.2.  But that means that if someone using such a code generator queries the analyzer to ask what the current language version is, they will get a more recent version than the version of the SDK.

> 
> Or can we add a mechanism to downgrade the default language version to analysis driver?

Yeah, that could work.  We wouldn't even need an API for it.  We could just say, for example, that when the analyzer is analyzing a library without an SDK constraint, instead of defaulting the language version to ExperimentStatus.currentVersion, it defaults it to Platform.version.

The idea would be that instead of thinking of ExperimentStatus.currentVersion as meaning "the current version of Dart" (which is an ill-defined concept anyway) we think of it as meaning "the latest version of Dart that this version of the analyzer understands".

**Comment by jakemac53** [comment]
Note that I did actually land a change to set the correct FeatureSet which is restricted to the current SDK version so at least it should not enable new features. The reported language version is still wrong though.

> We could just say, for example, that when the analyzer is analyzing a library without an SDK constraint, instead of defaulting the language version to ExperimentStatus.currentVersion, it defaults it to Platform.version.

This SGTM, but it does mean you require a `dart:io` import which I think is generally avoided? I don't know if analyzer cares about being able to run in environments where dart:io is not available or not.
