### ISSUE TITLE
Seamless build runner integration into monorepo 

### ISSUE THREAD

**Issue by roman-petrov** [dart-lang/build#2681]
I am not totally sure if I am requesting a feature or asking a question, and if it is a right place to ask.

I am developing a Flutter application and have several packages in my repository so it is packaged like a mono repository, but I am not using [mono_repo](https://github.com/dart-lang/mono_repo) though. 

I set up code generation in multiple packages so each package references `build_runner` package dependency in `pubspec.yaml` and packages now may have different `build_runner` versions.

In my current workflow I use Visual Studio Code [multi-root workspaces](https://code.visualstudio.com/docs/editor/multi-root-workspaces) to switch build runner context. 

Lets assume that `build_runner watch` in running in some package. If I change some source files in other package and need to update generated files I have to manually run `build_runner build` in that package which seems a little bit annoying.

The desired workflow which seems to be perfect for me: start build runner in watch mode for all packages so I can just edit any package and be sure that generated code is updated in background. 

As I understand, implementing such behavior might be a serious change and may require to directly integrate build runner into Dart SDK so users generally do not have to reference build runner directly in their packages/`pubspec.yaml`.

So I wonder if is this already possible somehow or can this be considered as a new feature request for Dart build system?

**Comment by jakemac53** [comment]
It is a quite ingrained principle in the build system right now that it is running at the root of exactly one package.

I would recommend creating a script or something which runs build_runner in each sub-package, or possibly filing a feature request for this in the mono_repo package (although you said you don't use that so it wouldn't help you). Note that the mono_repo package does support a `pub` command so you could today do `mono_repo pub run build_runner build` and that would build all projects, but `watch` would not work because it doesn't run all tasks in parallel and watch mode never exits until killed.

There are a lot of not so easy questions this would raise, such as how do interleave the build output of the different packages etc.

**Comment by jakemac53** [comment]
I am going to close this as not planned for now

**Comment by roman-petrov** [comment]
@jakemac53, thank you, currently I am already doing something like your suggestion. Just opened the issue as a feature request which might help to increase workflow with mono repositories & build runner. Hope  some improvements for this workflow will be available out of the box in future :)
