### ISSUE TITLE
Custom output location?

### ISSUE THREAD

**Issue by RedHatter** [dart-lang/build#2732]
I would like to create a builder that outputs files in a different directory than the input files. For example `dir1/file.ext1 -> dir2/file.ext2`. I attempted to use the following builder but I get `UnexpectedOutputException` errors. I would have expected the `build_to` option to allow setting a custom directory but that doesn't seem to be the case. Is this possible?

```
import 'package:build/build.dart';
import 'package:path/path.dart';

class ModelBuilder implements Builder {
  @override
  Future build(BuildStep buildStep) async {
    final inputId = buildStep.inputId;
    final contents = await buildStep.readAsString(inputId);
    await buildStep.writeAsString(
        AssetId(inputId.package,
          join('lib', 'models', basenameWithoutExtension(inputId.path) + '.dart')),
          '// Copied from $inputId\n$contents');
  }

  @override
  final buildExtensions = const {
    '.json': ['.dart']
  };
}
```

**Comment by jakemac53** [comment]
The outputs can only be expressed in terms of the `buildExtensions` map - which is a straightforward substitution of the file suffix.

When you output files they have to match exactly those declared outputs.

**Comment by simphotonics** [comment]
In order to write output to a custom directory and change the file extension,  you could use *synthetic input*. For more information about synthetic input see the section [Writing a Builder using a synthetic input](https://github.com/dart-lang/build/blob/master/docs/writing_an_aggregate_builder.md#writing-the-builder-using-a-synthetic-input
) found in the documentation of the Dart package [`build`](https://pub.dev/packages/build).

The field `buildExtensions` would then be something like:
```Dart
 @override
 Map<String, List<String>> get buildExtensions => {
        // Some logic to get all the outputs is required here. 
        // ...
        r'lib/$lib$': ['lib/models/file1.dart', ...] // <--  List all outputs here. 
      };
```
 If `dir1` and `dir2` are below `lib`, the key in the map above would be `rlib\$lib$`, otherwise `r$package$`.

In your `build` method you would then have only one buildStep and will have to resolve your inputs manually and iterate over
each input. 
```Dart
@override
  Future build(BuildStep buildStep) async {
    final Stream<AssetId> inputIds = await buildStep.findAssets(
      Glob('lib/dir1/*.json'), // Assuming that all *.json files in lib/dir1 are input files. 
    );
    
    await for (final inputId in inputIds) {
      final contents = await buildStep.readAsString(inputId);
      await buildStep.writeAsString(
        AssetId(inputId.package,
          join('lib', 'models', basenameWithoutExtension(inputId.path) + '.dart')),
          '// Copied from $inputId\n$contents');
      }
  }
```
I have written a builder where the output directory and name can be customized. You could have a look at: 
[`StandaloneBuilder`](https://pub.dev/documentation/merging_builder/latest/merging_builder/StandaloneBuilder-class.html).

But to be fair, synthetic input is more suitable for writing an aggregating builder. In that case, the map `buildExtensions` will contain only one value: the single output file.

**Comment by jakemac53** [comment]
I am going to close this issue in favor of https://github.com/dart-lang/build/issues/1689
