### ISSUE TITLE
Pub upgrade fails with build_web_compilers for null safety

### ISSUE THREAD

**Issue by jumperchen** [dart-lang/build#2925]
* Dart SDK Version (`2.12.0-29.10.beta`)

The error message:
```
Because build_web_compilers >=0.4.1 depends on logging ^0.11.2 and build_web_compilers <0.4.1 requires SDK version >=1.22.1 <2.0.0
  or >=2.0.0-dev.9 <2.0.0, every version of build_web_compilers requires logging ^0.11.2.
So, because socket_io_client depends on both logging ^1.0.0-nullsafety.0 and build_web_compilers any, version solving failed.
```

The workaround is to use `dependency_overrides` to override the package `logging` with version `1.0.0-nullsafety.0`, but this workaround cannot publish this library to pub.dev when running with `pub publish`.

Here is the error message for `pub publish`
```
Package validation found the following error:
* Your pubspec.yaml must not override non-dev dependencies.
  This ensures you test your package against the same versions of its dependencies
  that users will have when they use it.
```

**Comment by jakemac53** [comment]
I suspect we are going to see a lot more of these soon... the build packages are in a bit of a weird spot here. Usually a bottom  up migration would be recommended but that doesn't actually make sense for these packages since they aren't imported.

But they also aren't ready for null safety yet and we are going to end up needing to publish a bunch of times just to widen constraints on packages as they are released, and those are also pre-releases which we really shouldn't be allowing unless we also do a pre-release...

As a workaround for now, you could remove the overrides _and_ dev dependencies when publishing (make sure you can still successfully `pub upgrade` at that point).

**Comment by jumperchen** [comment]
@jakemac53 Is it possible to use two `pubspec.yaml` files for dev. and publish to solve the issue above?

**Comment by jakemac53** [comment]
Not that I am aware of.

**Comment by jakemac53** [comment]
Closing this as we have no actionable thing to do here - we are actively upgrading dependency constraints though as things get released
