### ISSUE TITLE
Consider reading enable-experiment from analysis_options.yaml

### ISSUE THREAD

**Issue by TimWhiting** [dart-lang/build#3036]
* Dart SDK Version  2.13.0-114.0.dev
* What package(s) from this repo you are using, and the version: build_runner 1.11.5
* What builder(s) you are using. Freezed (data classes) / JsonSerializable

I ran into issues trying to test freezed / json_serializable with the upcoming nonfunction-type-aliases
I set the enable-experiment in the analysis_options.yaml and set my min-sdk version correctly, but got errors trying to generate code with both of the following commands:

`dart run --enable-experiment=nonfunction-type-aliases build_runner build`
`dart --enable-experiment=nonfunction-type-aliases run build_runner build`
I got the error:
```
[SEVERE] freezed:freezed on lib/src/core/core/player.dart:

This builder requires Dart inputs without syntax errors.
However, package:game_scaffold_dart/src/core/core/player.dart (or an existing part) contains the following errors.
player.dart:6:18: Invalid generic function type.
player.dart:7:20: Invalid generic function type.
```
See the full reproducible example on [dart-lang/sdk](https://github.com/dart-lang/sdk/issues/44078#issuecomment-795785986)

Then I found out about the enable-experiment flag on build_runner build:

This command: `dart run build_runner build --enable-experiment=nonfunction-type-aliases`
works, and generates valid code, since there is nothing special about typealiases that the generator packages have to handle (For `typedef PlayerID = String` it doesn't matter if the generator produces `String` or `PlayerID`).

This isn't a problem that I expect many people to run into, unless they are trying to add support for new features into a generator package, or trying out new features of dart (even if the generated code has nothing to do with the new feature). But the main confusion is why do we have to add another command line option, when we already have to put it in the analysis_options.yaml to avoid syntax errors in the IDE and compilation errors on the commandline?

**Comment by jakemac53** [comment]
No other tools other than the analyzer read this file, so that would introduce a weird divergence. It is also a very explicit choice to require experiment flags on every invocation - it is a constant reminder that you are using an experiment and that your code may break at any time (experiment could be dropped, changed, whatever).

As far as the separate flags the reason is they do totally different things.

the `dart run --enable-experiment=<experiment>` flag enables the experiment for that script you are running (in this case it would be the build_runner script). This might break build_runner itself, etc, but would allow you to use the experiment in your _builder_ code.

The build_runner `--enable-experiment` flag allows you to enable the experiment for your _application_ code, without affecting the build_runner script itself.
