### ISSUE TITLE
Updating the package to be null-safety compatible, so far 1.12.2 is not.

### ISSUE THREAD

**Issue by inc16sec** [dart-lang/build#3061]
I'm using Flutter 2.0 and still at Dart sdk: ">=2.7.0 <3.0.0".
I was hoping to migrate to Dart sdk: ">=2.12.0 <3.0.0". and make my project null-safe, but in order to so all of the packages I'm using must be null-safe, including this one.
When I run the command 
```
flutter pub outdated --mode=null-safety
```

It shows me a list of all the packages that are yet to be updated to support null-safety, int the case of build_runner, it shows
```
dev_dependencies:
build_runner   ✗1.12.2     ✗1.12.2     ✗1.12.2              ✗1.12.2  
```

So I'm wondering is there something that needs to be done from my side or I need to wait for an update of the package that supports null-safety. THANK YOU.

**Comment by MohammadEzoo** [comment]
any update ?

**Comment by sibylantoninobajeli** [comment]
Hi folks,
I'm facing the same problem.

My flutter doctor:
`[√] Flutter (Channel beta, 2.1.0-12.2.pre, on Microsoft Windows [Versione 10.0.19041.867], locale it-IT)
    • Flutter version 2.1.0-12.2.pre at c:\flutter
    • Framework revision 5bedb7b1d5 (10 days ago), 2021-03-17 17:06:30 -0700
    • Engine revision 711ab3fda0
    • Dart version 2.13.0 (build 2.13.0-116.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\abajeli\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.51.0)
    • VS Code at C:\Users\abajeli\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.16.0
`

YAML:
`
  freezed_annotation: ^0.14.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.12.2
  freezed: ^0.14.1+1
  json_serializable: ^4.0.1
`

**Error**
_
Failed to precompile build_runner:build_runner:
/c:/flutter/.pub-cache/hosted/pub.dartlang.org/build_runner-1.12.2/bin/build_runner.dart:91:49: Warning: Operand of null-aware operation '??' has type 'bool' which excludes null.
    var verbose = parsedArgs.command['verbose'] as bool ?? false;
                                                ^
/c:/flutter/.pub-cache/hosted/pub.dartlang.org/build_runner-1.12.2/bin/build_runner.dart:101:9: Warning: Operand of null-aware operation '?.' has type 'StreamSubscription<dynamic>' which excludes
null.
 - 'StreamSubscription' is from 'dart:async'.
  await logListener?.cancel();
        ^
Error: Cannot run with sound null safety, because the following dependencies
don't support null safety:

 - package:build_runner_core
 - package:build_runner
 - package:build_config
 - package:build_daemon
 - package:code_builder

For solutions, see https://dart.dev/go/unsound-null-safety
/c:/flutter/.pub-cache/hosted/pub.dartlang.org/build_runner-1.12.2/bin/build_runner.dart:91:37: Error: Operator '[]' cannot be called on 'ArgResults?' because it is potentially null.
 - 'ArgResults' is from 'package:args/src/arg_results.dart' ('/C:/flutter/.pub-cache/hosted/pub.dartlang.org/args-2.0.0/lib/src/arg_results.dart').
    var verbose = parsedArgs.command['verbose'] as bool ?? false;
                                    ^
pub finished with exit code 1
_

**Comment by dhrn** [comment]
+1

**Comment by yakupbaser** [comment]
any update?

**Comment by bismarabia** [comment]
++++

**Comment by msiviero** [comment]
+

**Comment by Puspharaj** [comment]
bump

**Comment by cyberpwnn** [comment]
+1

**Comment by mergengerel** [comment]
+1

**Comment by donyaie** [comment]
+1

**Comment by yusuke0505** [comment]
👀

**Comment by brynjen** [comment]
+1

**Comment by CodeDoctorDE** [comment]
Please use the reaction function instead of comment on this issue. It's annoying if you subscribe to this issue!

**Comment by larssn** [comment]
@kevmoo Sorry for the ping, but I can see you've worked on null safety for this repo. Do you have anything you can share?
Thanks!

**Comment by jakemac53** [comment]
You can safely ignore these messages from `pub outdated`. As long as your package does not import `package:build_runner` directly  you are fine to migrate.

The user importable packages have been migrated.

**Comment by sarbogast** [comment]
@jakemac53 But won't it still make Flutter run in unsound null safety mode just because there is a dependency that's not null safe?

**Comment by kevmoo** [comment]
> @jakemac53 But won't it still make Flutter run in unsound null safety mode just because there is a dependency that's not null safe?

@sarbogast – there is no RUNTIME dependency, so it's not an issue.
