### ISSUE TITLE
build_config v1.0.0

### ISSUE THREAD

**Issue by evanweible-wf** [dart-lang/build#3073]
👋   Hi there! I know you all are working on a bunch of NNBD migrations, but just wanted to check in on build_config. I saw that it [has been migrated](https://github.com/dart-lang/build/blob/master/build_config/CHANGELOG.md#100-dev), but at one point was maybe just [waiting on build v2 to be released](https://github.com/dart-lang/build/blob/master/build_config/pubspec.yaml#L32-L36)? Since that has happened, would it be possible to release build_config 1.0.0 or is it still waiting on something else?

**Comment by jakemac53** [comment]
The plan is to release all the null safety migrations at the same time (otherwise we end up with a lot of churn, if I released build_config now I would have to release every package that depends on it as well).

I think the main blocker left is package:code_builder getting a published version, we currently depend on the master branch of that package to use its pending nnbd release.

**Comment by evanweible-wf** [comment]
Gotcha, that makes sense - thanks!
