### ISSUE TITLE
linter 'always_specify_types' flags Map

### ISSUE THREAD

**Issue by buttonsrtoys** [dart-lang/build#3098]
Dart package 'lint' flags the generated line below when 'always_specify_types' is set

    Sample _$SampleFromJson(Map json) {  // <- Specify type annotations
      return Sample(
        json['key'] as int?,
        json['report'] as String?,
      );
    }

changing first generated line to below fixes the problem

    Sample _$SampleFromJson(Map<String, dynamic> json) {  

* Dart SDK Version (`dart --version`) 
2.12.3

* What package(s) from this repo you are using, and the version (i.e. `build_runner 0.7.12`)
2.0.1

* What builder(s) you are using (or writing yourself). Try to give a short summary of what they do.
* Whether you are using Windows, MacOSX, or Linux (if applicable)
Windows

* Whether you are using Chrome, Safari, Firefox, Edge (if applicable)
* Any other packages or constraints we should know about

**Comment by jakemac53** [comment]
Note that this package does support maps coming from YAML which doesn't have string keys. I would recommend `Map<Object?, Object?>`.

**Comment by natebosch** [comment]
In general most builders won't make guarantees that they follow all possible lints. In particular lints like `always_specify_types` conflict with other lints that are more idiomatic.

I think this issue is asking for a specific builder to either conform to this lint or to suppress it - those issues need to be filed with the individual projects that implement the builders. I don't think this is actionable on this repository, so I will close it for now.
