### ISSUE TITLE
Build performance - where is the bottleneck?

### ISSUE THREAD

**Issue by daniel-v** [dart-lang/build#3153]
```
Dart SDK version: 2.13.4 (stable) (Wed Jun 23 13:08:41 2021 +0200) on "linux_x64"
build_runner:
    version: "1.11.1"
build_runner_core:
    version: "6.1.7"
```

Hello there!

I wanted to see if I could gain some compilation speed for my web projects that heavily rely on build_runner and builder ecosystem. Figured, more memory, faster CPU or maybe some M.2 SSDs could help. But first, I wanted to see if spending money is worth it, so I set up a VM and started playing around.

## Methodology

Set up a VM which received 14G RAM and different number of cores for different tests. The VM runs on an SSD, quite average really. Cloned `angular_components` (yeah, I know, I know, migrating away but was an easy entry point now) and started running build.

```sh
# command to build
git clean -fdx && pub upgrade && /usr/bin/time -v dart run build_runner build web
```

**Is more CPU cores better?**

Between 8, 12 and 24 cores, I saw barely any difference.

```
# 24 core
[INFO] Succeeded after 1m 1s with 8331 outputs (16406 actions)
	Command being timed: "dart run build_runner build web"
	User time (seconds): 155.28
	System time (seconds): 58.34
	Percent of CPU this job got: 231%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 1:32.43
# 8 core
[INFO] Succeeded after 1m 3s with 8331 outputs (16406 actions)
	Command being timed: "dart run build_runner build web"
	User time (seconds): 140.22
	System time (seconds): 64.40
	Percent of CPU this job got: 217%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 1:34.13
```

My conslusion is that the build system is probably doesn't utilize many cores too well.

**Q:** is this assumption correct?

**Is disk IO holding it back?**

I first traced all the disk file opens with strace

```sh
strace -f -t -e trace=file dart run build_runner build web 2>&1 | grep -oP '(?<=openat\(AT_FDCWD, ")([^"]+)'
```

I saw a few places where there were a lot of reads. `.pub-cache`, `/tmp` for scratch and temporary files, sdk path and project root.

Let's go!
```sh
# fstab entry to have /tmp in memory
tmpfs /tmp tmpfs defaults,noatime,nosuid,nodev,noexec,mode=1777,size=2G 0 0
# create another tmpfs for .pub-cache and project
mkdir /mnt/tmpfs
sudo mount -t tmpfs -o size=3000m tmpfs /mnt/tmpfs
# set pub cache location
export PUB_CACHE=/mnt/tmpfs/.pub-cache
# move project, sdk, etc, files to /mnt/tmpfs
```
Verified with strace again where file opens are and found that these are pretty much the only ones that are not on an in-memory FS:

```
/lib/x86_64-linux-gnu/libdl.so.2
/lib/x86_64-linux-gnu/libpthread.so.0
/lib/x86_64-linux-gnu/libm.so.6
/lib/x86_64-linux-gnu/libc.so.6
/sys/devices/system/cpu/online
/proc/sys/vm/max_map_count
/proc/self/maps
/dev/urandom
/home/MY_USER/.dart/dartdev.json
/etc/nsswitch.conf
/etc/host.conf
/etc/resolv.conf
/lib/x86_64-linux-gnu/libnss_files.so.2
/etc/hosts
/lib/x86_64-linux-gnu/libnss_mdns4_minimal.so.2
/lib/x86_64-linux-gnu/libresolv.so.2
/lib/x86_64-linux-gnu/libnss_dns.so.2
/etc/gai.conf
/etc/ssl/certs/1001acf7.0
/etc/localtime
/etc/ssl/certs/4a6481c9.0
```

The result is:

```
# 8 core VM
[INFO] Succeeded after 1m 3s with 8331 outputs (16406 actions)
	Command being timed: "dart run build_runner build web"
	User time (seconds): 143.07
	System time (seconds): 62.70
	Percent of CPU this job got: 214%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 1:35.76
```

Seems that it's not disk IO either. I would have expected to have some kind of gain here, after all, everything is in memory as far as I could tell.

Double checking my results on bare-metal linux install and received very similar results (times were different but the delta between different measurements were consistent with these).

**Q:** if it's not disk IO and more cores don't seem to help, what could be the bottleneck?

Thanks in advance!

**Comment by jakemac53** [comment]
Normal builders are all single threaded - unless the builder itself does multi-threading. This is because they all share an analysis context, which we can't share across isolates/processes. We do use multiple process for compilation (in build_web_compilers for instance), but not for code generation.

Angular specifically relies very heavily on the analyzer - it fully resolves all files in your package _and all your dependencies that depend on angular_. This makes it uniquely poor in terms of performance, compared to other builders which usually only operate on the root package.

The way package:build works there is a high cost (O(transitive deps)) for each file resolved in this way. They do share work with other libraries but the overall cost is the same still due to how we do invalidation. Since any transitive dep can change how the library would invalidate, we have to set up dependencies on all the transitive deps for each of these files. In theory something better could be done there, but we haven't investigated it (and it would be a very large body of work across multiple teams to do so).

**Comment by daniel-v** [comment]
@jakemac53 thank you for your answer!

I'm just trying to dig a bit deeper. You mentioned invalidation. I assume you are talking about cache invalidation which seems quite an important piece of incremental builds. Am I right in that assumption?

I purposefully limited the scope of exploring the code for a single use-case: CI/CD build times, first-builds, where there are no prior build caches, everything has to be done from scratch. 

My understanding how build process works is that it computes upfront how we can get to the desired output and what "actions" are needed to be taken given a set of inputs from a set of packages. There is  `PackageGraph`, `AssetGraph`, `TargetGraph` and all that kind of goodies that seem to support that. The build process is split into `BuildPhase`s which, in the end, is a flatted list of "things" that needs to be done. `BuildImpl#_runPhases` takes that list of things and just runs it:

```dart
// this is not what the code looks like but in behavior, it is similar
for (var phaseNum = 0; phaseNum < _buildPhases.length; phaseNum++) {
  // ...
  outputs.addAll(await _runBuilder(phaseNum, phase, primaryInputs));
  // ...
}
```

It is probably super-naive to ask: if we can iterate over the phases and run the builders as such, couldn't we work with a non-flattened list of phases, maybe keep the strongly connected components' structure and run _some_ of them in parallel? 

All in all, I think what is important to express here, with such limited insight into the technical implementation, is that I'd be super-super happy if the build times could be reduced. I'm sitting on top of 12 cores, 24 threads, I'd rather listen to my cooler scream and see thermal throttle than sit 5 mins on top of a build (20+ on CI with all the tests).

**Comment by jakemac53** [comment]
> I'm just trying to dig a bit deeper. You mentioned invalidation. I assume you are talking about cache invalidation which seems quite an important piece of incremental builds. Am I right in that assumption?

Correct, its about knowing what files need to be regenerated when a given file changes. Today this requires an explicit edge to be set up from any given file to all the files it needs to invalidate (we call these its "outputs").

> I purposefully limited the scope of exploring the code for a single use-case: CI/CD build times, first-builds, where there are no prior build caches, everything has to be done from scratch.

Yes, fwiw this is not the case we optimize for today, as it is considered the less important case than the incremental build case, which is the more common dev experience.

> My understanding how build process works is that it computes upfront how we can get to the desired output and what "actions" are needed to be taken given a set of inputs from a set of packages. There is `PackageGraph`, `AssetGraph`, `TargetGraph` and all that kind of goodies that seem to support that. The build process is split into `BuildPhase`s which, in the end, is a flatted list of "things" that needs to be done. `BuildImpl#_runPhases` takes that list of things and just runs it:

Correct, in this phase we compute the "primary inputs", which are the files that directly cause a certain output to be generated (this is based on the build extension mappint). During the actual generation of those outputs we compute additional "secondary inputs" which are any other file which is read during the creation of that file. We also need to invalidate the output when any of these changes. This is the problematic part when you use analyzer - that list becomes all transitively reachable inputs today.

> It is probably super-naive to ask: if we can iterate over the phases and run the builders as such, couldn't we work with a non-flattened list of phases, maybe keep the strongly connected components' structure and run _some_ of them in parallel?

We actually basically do not run "optional" builder phases in sequence. Those phases are just entirely skipped, and we run the builders lazily for them _on demand_. Only the "required" phases are actually run in sequential order. In practice we keep the CPU 100% busy anyways, so there is little advantage to further parallelization - unless we had a multi-core approach then we could possibly get some advantage there. But we don't support parallelization due to the shared analysis context. Note that creating an analysis context for each core would dramatically increase memory consumption as well.

> All in all, I think what is important to express here, with such limited insight into the technical implementation, is that I'd be super-super happy if the build times could be reduced. I'm sitting on top of 12 cores, 24 threads, I'd rather listen to my cooler scream and see thermal throttle than sit 5 mins on top of a build (20+ on CI with all the tests).

Ya, I understand that things can be pretty slow today, especially for larger angular projects. But we don't currently have any plans to improve the situation directly.

Instead of trying to improve build_runner I am trying to add macros to the language, which should dramatically reduce build times, especially compared to analyzer based builders. Hopefully most Dart codegen builders can move to that feature eventually (although it is unlikely angular would push anything externally at this stage, unfortunately).

**Comment by daniel-v** [comment]
Once again, thanks for taking the time to answer.

Don't worry about Angular. It was the easiest to access as build heavy package.

M.. macros? I stutter a bit when I say that word. Is this different from static metaprogramming?

**Comment by jakemac53** [comment]
> M.. macros? I stutter a bit when I say that word. Is this different from static metaprogramming?

Macros are the current thinking for how we want to enable static metaprogramming, yes.

**Comment by jakemac53** [comment]
I am going to close this issue as I don't think there is anything we are planning to do in this space currently.
