### ISSUE TITLE
source_gen tests broken by making BuildStep sealed 

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/build#3160]
See https://github.com/dart-lang/source_gen/blob/07327d7c3fac3e7d6940817ec1fba3dda09ac6ea/source_gen/test/builder_test.dart#L663.

We should see if we can rewrite the test a different way, or if we should unseal the class.

cc @simolus3 @kevmoo @natebosch

**Comment by simolus3** [comment]
The `_TestBuildStep` is only used in [this test](https://github.com/dart-lang/source_gen/blob/07327d7c3fac3e7d6940817ec1fba3dda09ac6ea/source_gen/test/builder_test.dart#L555-L565), which looks straightforward to replace with `runBuilder`. I can open a PR for that.

IMO making `BuildStep` sealed is justified because we don't consider adding new methods to it breaking, so we should communicate that to users.

**Comment by jakemac53** [comment]
Sounds good to me 👍 . I agree sealing it is best.
