### ISSUE TITLE
Unskip tests that expect InconsistentAnalysisExceptions

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/build#3202]
See discussion in https://github.com/dart-lang/build/pull/3199. These are skipped for now until analyzer starts throwing the error again or we can figure out a better way to repro the test.

**Comment by natebosch** [comment]
The reason none of these behave as expected is that we aren't calling `driver.changeFile`.

We don't really have access to the `driver` in these tests, so if we want to test for this exception we'd either need to expose more internals, or make the tests more complicated so that they run across multiple actions.

I'm somewhat inclined to drop the tests instead, they don't feel like a realistic example of how this exception can crop up and I don't know what value they bring if we unskip them.

**Comment by jakemac53** [comment]
I would be fine with removing them
