### ISSUE TITLE
`build.yaml` schema

### ISSUE THREAD

**Issue by andreiborisov** [dart-lang/build#3217]
It would be nice to provide a publicly available schema for `build.yaml` as currently VS Code extension assumes it's a completely different schema (when using schemastore.org) which leads to analyzer reporting errors incorrectly.

> Dart SDK Version (`dart --version`)
```
Dart SDK version: 2.15.0-116.0.dev (dev) (Thu Sep 16 09:47:01 2021 -0700) on "macos_x64"
```
> What package(s) from this repo you are using, and the version (i.e. `build_runner 0.7.12`)

`build_runner: ^2.1.4`, however, it's more concerned to `build_config` I think.

> What builder(s) you are using (or writing yourself). Try to give a short summary of what they do.

Not applicable.

> Any other packages or constraints we should know about

No.

**Comment by evanweible-wf** [comment]
I've been using this for a while: https://json.schemastore.org/dart-build.json

I don't know who created it, I don't think it's exhaustive, and I know there's at least one inconsistency with the recommendations (it expects builder names to be in the form `<pkg>|<builder>` instead of `<pkg>:<builder>`), but it'd be a good starting point.

**Comment by simolus3** [comment]
SchemaStore provides a [catalog of schemata](https://www.schemastore.org/api/json/catalog.json) that maps a file name to a JSON/YAML schema.  Initially, `build.yaml` files resolved to that Dart build schema but we had to [revert that](https://github.com/SchemaStore/schemastore/issues/1163) because other tools are using `build.yaml` too. It unfortunately looks like another schema (Hammerkit) was assigned to that pattern now. I'm using this in VS Code settings to use the correct schema:

```json
    "yaml.schemas": {
        "https://json.schemastore.org/dart-build": [
            "build.yaml"
        ]
    },
```

Something similar is possible for IDEA-based tooling too, but I don't think we can do much about the default being wrong.

> (it expects builder names to be in the form `<pkg>|<builder>` instead of `<pkg>:<builder>`)

I wrote the `build.yaml` schema on SchemaStore, and my understanding was that we prefer `:` for targets and `|` for builders. I took that from [the yaml format in this repo](https://github.com/dart-lang/build/blob/master/docs/build_yaml_format.md#builderkey). If you notice more issues with that schema, I'm happy to fix them :)

I can also open a PR to add a revised schema to this repository, but I'm not sure how helpful that is in the end. To use it in popular tools it needs to be a SchemaStore. At least we'd have a specification that's known to be correct then.

**Comment by jakemac53** [comment]
Thanks for the clarification, it does seem like we wouldn't get a ton of value out of having a schema stored here. It might stay more up to date though.

What would really be cool is if we could auto-generate the schema off of the classes that we use to parse it :D.

**Comment by jakemac53** [comment]
Maybe we should make an FAQ entry at least describing how you can point your IDE at the correct schema?

**Comment by evanweible-wf** [comment]
> I wrote the build.yaml schema on SchemaStore, and my understanding was that we prefer : for targets and | for builders. I took that from the yaml format in this repo.

Oh sorry I totally missed the difference between TargetKey and BuilderKey, thanks for the clarification!

> Maybe we should make an FAQ entry at least describing how you can point your IDE at the correct schema?

👍  fwiw I do the same thing as @simolus3 in VS Code

**Comment by jakemac53** [comment]
If one of you is familiar with how it works could send a PR that would be great! Then I can set it up for myself too, haha :).
