### ISSUE TITLE
FileDeletingBuilder seems to have no effect

### ISSUE THREAD

**Issue by wujek-srujek** [dart-lang/build#3298]
I have a custom builder pipeline that:
1. Creates a couple of temporary files in cache (builder 1)
2. Collects these temporary files and generates a single file based on them (builder 2, applied by builder 1).
3. Post process cleanup of the temporary files created by builder 1 (`FileDeletingBuilder`).

The pipeline works fine, except that I don't see any real difference whether I apply the post process cleanup or not - the only change is a slight difference in summary output after the build:
`[INFO] Succeeded after 152ms with 3 outputs (3 actions)` (no post process cleanup)
vs
`[INFO] Succeeded after 164ms with 3 outputs (5 actions)` (with cleanup).
(I haven't tried to reverse engineer the cache and other directories created by the build process so no idea what changes there.)

The files are not deleted. I read that they actually shouldn't be here https://github.com/dart-lang/build/blob/master/docs/builder_author_faq.md#how-can-i-have-temporary-outputs-only-used-during-the-build, but I fail to understand the consequence of using vs not using the cleanup.

Why would I care about 'deleting' the temp files if they stay on disk? Is it possible to any builder (not post-process builder) to run after the cleanup and see the files that it shouldn't?
What is the 'development server' that FAQ entry mentions, that would not show the 'deleted' outputs?

**Comment by jakemac53** [comment]
@wujek-srujek The files are only marked as deleted, but not actually deleted, which means if you do `-o <output-dir>` they will not be copied there, and also the `serve` mode will refuse to serve the files.

We don't want to actually delete the files because then we would have to regenerate them for future builds that need them as inputs.

Said another way, it "deletes" the files as far as the build system is concerned, making them not final build outputs. But it does not actually physically delete the files from disk because there is no need to (the cache dir is an implementation detail).

**Comment by jakemac53** [comment]
I should have read your entire comment before answering haha.

To more directly answer your question, it matters primarily for deployment, on the Web in particular.

This package allows you to create a merged output directory for deploying your app, which combines all the generated to cache files and source files into a single directory, as well as all files from all your dependencies.

If a file is "deleted" by a post process builder, it will not show up in those output directories, and it also will not show up in the dev server which is what you get if you do `dart run build_runner serve`.

Generally this only applies to web projects today.

**Comment by wujek-srujek** [comment]
Does it make any difference when all I do is call '... build_runner build' or 'watch', in a pure Dart or a Fluter app? And yes, the `--output` flag does show the difference, it's just I have never had to use it.

**Comment by wujek-srujek** [comment]
All clear now, thanks.

**Comment by jakemac53** [comment]
> Does it make any difference when all I do is call '... build_runner build' or 'watch', in a pure Dart or a Fluter app? And yes, the `--output` flag does show the difference, it's just I have never had to use it.

For flutter in particular it does not ever make a difference, because flutter never sees generated to cache files and it also never sees merged output directories afaik. It used to matter for flutter web when they used build_runner, but they no longer do.

For "pure Dart" it only matters if you use the `dart run build_runner run` command which _does_ work with generated to cache files. But if you just do `dart run` then it won't work with generated to cache files. You could create a merged output dir for a pure dart app and deploy it that way or something, in which case it would matter.
