### ISSUE TITLE
Remove the `phase` concept

### ISSUE THREAD

**Issue by natebosch** [dart-lang/build#333]
As build_runner's asset graph gets smarter we should need to rely less on having a 'phase' done before running further builders because we can avoid reading or listing the wrong assets based on the graph rather than strictly what exists on disk.

We should replace the `Phase` with a `BuildAction`, and possibly the `PhaseGroup` should just be a `List<BuildAction>`.

I think I've only seen phases which consist of a single build action anyway - but if there are uses cases we think we'd be losing we should take a close look.

**Comment by natebosch** [comment]
maybe we should front-load this?

I did a quick look through Github and could only find a couple examples of multiple actions in a phase - and those struck me as likely a performance optimization rather than a logical need. Our bazel integration already handles this as a `List<Builder>` (though more complex structures can be build up through bazel targets I suppose).

Every consumer of this package will be impacted if we change the argument to `List<BuildAction>` but IMO that's the nicer api. If we keep it as `PhaseGroup` then we could write it in a way that may not be breaking for many authors but keeps an API that loses it's value in the long term...

**Comment by matanlurey** [comment]
I'd do it now rather than later if the ergonomics are worth it (I'd argue they are)

**Comment by jakemac53** [comment]
Ya, afaik the only reason for multiple builders in a phase is a performance optimization.

As we discussed earlier since files can't be edited we can actually automatically give this benefit by default by running actions earlier. They would only block on a previous "phase" when you actually ask for a generated asset which is not ready yet, or if you list all assets in a package.
