### ISSUE TITLE
Allow wildcards in the output filenames

### ISSUE THREAD

**Issue by fischerscode** [dart-lang/build#3455]
I want to generate a (`.json`) file for each class in a `.dart` file.

It seems like this is currently not possible. *[restrictions](https://github.com/dart-lang/build/blob/master/docs/writing_a_builder.md)*

I think it would be create, if wildcards would be allowed in the output filenames.

**Comment by jakemac53** [comment]
Another, possibly crazier idea to explore could be the ability to ask for all the outputs of a specific action. So essentially, instead of globbing for the JSON files produced by a Dart file, you could say "give me the list of outputs for this Builder + Input". This would be the only way to get access to the files, so they would be special in that way. Asking for the list of outputs is what would trigger the action to build them, and only a builder which asked for that list in that way would have the ability to read them.

This wouldn't cover all use cases though, but if those outputs are only _secondary_ inputs to other actions, then it should generally work out. Unless they were Dart files which we expect to be able to just read based on seeing the import to them.

**Comment by jakemac53** [comment]
Another case that makes this challenging:

**Builder A**: converts `*.dart to` `*.<class-name>.json` (creates some json output for each class)
**Builder B**: converts `*.json` to `*.<member-name>.json` (extracts per member info into smaller json files)

In this case, we have a whole extra layer of wildcard outputs. This could continue to go on several layers deep. Efficiently understanding that when we ask to build `foo.<class-name>.<member-name>.json` in this example, requires running Builder A on `foo.dart` and then Builder B on `foo.<class-name>.json` is non-trivial, especially if we want to to perform reliably and scale well.

**Comment by fischerscode** [comment]
I see, seems like I stumble from one challenge into another. 😆 

For now, I'm only allowing one class per file. (resulting in only one output)

> Could be a fun problem though.

I might have a look at it at the end of the week, but it seems like there are use cases I didn't had I mind, back when I thought about it and.
