### ISSUE TITLE
Logging Breaking Change

### ISSUE THREAD

**Issue by kaj777** [dart-lang/build#3518]
##### Description

https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator-gradle-plugin/README.adoc
using dart dio generator

Generate was working fine all the time until today, no code change but this sudden issue occur at build_runner.
Does anyone encounter the issue ?

Possible Reason :https://pub.dev/packages/logging/changelog the new release here seems to break things.

command : flutter pub run build_runner build

 build_runner 2.3.3 (2.4.4 available)
 build_runner_core 7.2.7 (7.2.9 available)

> Task :runBuildRunner
Failed to build build_runner:build_runner:
../../../../../.pub-cache/hosted/pub.dev/build_runner_core-7.2.7/lib/src/logging/build_for_input_logger.dart:13:7: Error: The non-abstract class 'BuildForInputLogger' is missing implementations for these members:
 - Logger.onLevelChanged
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class BuildForInputLogger implements Logger {
      ^^^^^^^^^^^^^^^^^^^
../../../../../.pub-cache/hosted/pub.dev/logging-1.2.0/lib/src/logger.dart:162:22: Context: 'Logger.onLevelChanged' is defined here.
  Stream<Level?> get onLevelChanged {
                     ^^^^^^^^^^^^^^
pub finished with exit code 1

> Task :runBuildRunner FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':runBuildRunner'.
> Process 'command 'flutter'' finished with non-zero exit value 1

##### Steps to reproduce

 flutter pub run build_runner build

**Comment by danw8989** [comment]
Having the same problem but only in github actions. On my local dev env, it builds fine...

**Comment by christianruppertneo** [comment]
Same issue here, only on CI/CD - but I guess thats due to having other versions cached locally. Our error is a bit different, but also suddenly appeared and broke our builds:

`Failed to build build_runner:build_runner:
../../../../../.pub-cache/hosted/pub.dev/build_runner_core-7.2.7/lib/src/logging/build_for_input_logger.dart:13:7: Error: The non-abstract class 'BuildForInputLogger' is missing implementations for these members:
 - Logger.onLevelChanged
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.
class BuildForInputLogger implements Logger {
      ^^^^^^^^^^^^^^^^^^^
../../../../../.pub-cache/hosted/pub.dev/logging-1.2.0/lib/src/logger.dart:162:22: Context: 'Logger.onLevelChanged' is defined here.
  Stream<Level?> get onLevelChanged {
                     ^^^^^^^^^^^^^^
pub finished with exit code 1`

**Comment by lburakowski** [comment]
I'm having the same problem. I found a workaround by overriding the following dependencies in my pubspec.yaml:

```yaml
dependency_overrides:
  logging: 1.1.1
  build_runner_core: 7.2.8
```

**Comment by oscarshaitan** [comment]
If you have that issue in a core lib, all your project should have the overrides, while you update our local to the newest Flutter / Dart version.

If I'm not wrong, this issue is due to a transitive dependency that is taken the newest version and that versions is prepared for the new Flutter / Dart version.
> It happens also on my local, any idea why?
> 
> dependency_overrides: logging: 1.1.1 this temporary workaround works locally but since I'm re-creating the api package on cicd build, the yaml would get overriden

**Comment by kaj777** [comment]
thanks, flutter upgrade to the latest version solves the issue.
should it be that the generator library should depend on a fix build runner version instead of _any_  version  in pubspec to avoid issue introduce by such breaking change? As for now we are forced to perform upgrade.

**Comment by jakemac53** [comment]
This should be resolved now, thanks to @natebosch for the fix last night!

If you do have any dependency overrides please remove them and retry a `dart pub upgrade`. You won't want to leave those in long term because they will cause other problems later.

If you are still experiencing issues after upgrading please let us know.
