### ISSUE TITLE
PostProcessingBuilder with Custom Build Script

### ISSUE THREAD

**Issue by samyakkkk** [dart-lang/build#3533]
* Dart SDK Version (`dart --version`)
Dart SDK version: 3.0.0 (stable) (Thu May 4 01:11:00 2023 -0700) on "macos_arm64"
* What package(s) from this repo you are using, and the version (i.e. `build_runner 0.7.12`)
```
 build: 2.4.1
 build_config: 1.1.1
 build_runner: 2.4.4
 build_runner_core: 7.2.10
```
* What builder(s) you are using (or writing yourself).
I'm using a normal Builder (LibraryBuilder from sourcegen) followed by a PostProcessingBuilder
* Whether you are using Windows, MacOSX, or Linux (if applicable)
MacOS
----
We're using a custom script containing of one builder that inputs `.dart` files and saves a processed version `.save_wt.dart`  in the `cache`. We want to add a PostProcessingBuilder that inputs the '. save_wt.dart` files, processes them and then deletes the primary output.

The primary builder runs but the post processing builder `DeleterBuilder` is never triggered. Trying to find out what is the flaw in our configuration?

Note: this is a package users are supposed to integrate into their dart projects and run using `dart run welltested:save build`

bin/save.dart:
```
import 'package:build_runner_core/build_runner_core.dart' as build_runner_core;
import 'package:welltested/builder.dart' as welltested;
import 'package:build_runner/build_runner.dart' as build_runner;
import 'dart:io' as io;

final _builders = <build_runner_core.BuilderApplication>[
  build_runner_core.apply(r'welltested:save', [welltested.saverBuilder],
      build_runner_core.toDependentsOf(r'welltested'),
      hideOutput: true, appliesBuilders: ['welltested:deleterBuilder'])
];
Future<void> main(List<String> args) async {
  build_runner_core.overrideGeneratedOutputDirectory('welltested_save_cache');
  final result = await build_runner.run(args, _builders);
  io.exitCode = result;
}
```

builder.dart:
```
Builder saverBuilder(BuilderOptions options) {
  return LibraryBuilder(SaverBuilder(),
      allowSyntaxErrors: true,
      options: BuilderOptions({
        "build_extensions": {
          '.dart': ['.save_wt.dart'],
        }
      }));
}

PostProcessBuilder deleterBuilder = DeleterBuilder();

///Simpleifed version for reference
class DeleterBuilder extends PostProcessBuilder {
  @override
  FutureOr<void> build(PostProcessBuildStep buildStep) async {
    final assetId = buildStep.inputId;
    print("deleter builder ${assetId.path}");
  }

  @override
  Iterable<String> get inputExtensions => ['.save_wt.dart'];
}

```

build.yaml (of the package)
```
post_process_builders:
  deleterBuilder:
    import: 'package:welltested/builder.dart'
    builder_factory: 'deleterBuilder'
    input_extensions: [".save_wt.dart"]
```

Thanks in advance.

**Comment by jakemac53** [comment]
I don't see anything obviously wrong with your configuration there - are you sure the builder didn't run the first time, and we simply aren't running it again because we don't need to re-run it? If you do a `dart run welltested:save build -o <dir>` do you see the files in that output directory? When you "delete" files in post process files they are not actually deleted - they are only marked as not being a part of any final build, so they won't be a part of the output directory but they still exist on disk at their original location.

Note also that package:build does come with a `FileDeletingBuilder` which you can use for basic stuff like this, see how build_web_compilers uses it here https://github.com/dart-lang/build/blob/master/build_web_compilers/lib/builders.dart#L69 and here https://github.com/dart-lang/build/blob/master/build_web_compilers/build.yaml#L142. It doesn't save a ton of work but it supports being enabled/disabled for release/dev modes and exclude globs.

**Comment by samyakkkk** [comment]
@jakemac53 aside from this issue, a simple solution for our usecase can be to re run the SaverBuilder every time without maintaining any cache.

Is there a simple way that I can do this? some configuration that auto invalidate cache and then reruns the SaverBuilder completely.

**Comment by jakemac53** [comment]
Oh, I just realized why this isn't running. Since you have a custom build script, you need to include this builder in that script. You can apply it using the `applyPostProcess` api from build_runner_core. You may not need the build.yaml configuration at all given you have a custom build script (although don't quote me on that).

> @jakemac53 aside from this issue, a simple solution for our usecase can be to re run the SaverBuilder every time without maintaining any cache.

No we don't have an option for this, it kind of goes against the fundamental structure of the package. A builder should always generate the same thing with the same inputs.

You could fake something by like having your script put a timestamp into a file before each build, and then have your builder read that file.

**Comment by samyakkkk** [comment]
I updated the custom build script to 

```
post_process_builders:
  deleterBuilder:
    import: 'package:post_builders/builders.dart'
    builder_factory: 'deleterBuilder'
    input_extensions: [".save_wt.dart"]
```

Still no luck, the deleterBuilder just doesn't run. I tried multiple variations with and without the build.yaml and it just doesn't seem to trigger. 

I've updated the code in https://github.com/samyakkkk/post_builders to help reproduce the issue.
