### ISSUE TITLE
Integrate with IDE extensions to run code-generation by hand on a per-file basis

### ISSUE THREAD

**Issue by rrousselGit** [dart-lang/build#3545]
Hello!

This is general feedback I received from a lot of people while discussing offline at the FlutterCon Berlin:
Folks would like to be able to update generated code manually on a per-file basis from their IDE

The idea is that:
- The IDE is already using the analyzer
- Since it uses the analyzer, it should be able to run code-generators manually for a specific "library"
- The CI could be used to check if any generated file is outdated.
   An IDE could also have a slow background process checking if a given library has out-of-date generated code.

This would allow a fast path for updating code for a specific file, reducing the frustration of having to wait minutes in some cases.

cc @DanTup

**Comment by rrousselGit** [comment]
On build's side, maybe it would be a matter of having an alternative to `build_runner#run`, like a "runBuildersForLibraries":

```dart
Future<void> runBuilderForLibraries(List<BuilderApplication> builders, List<ResolvedLibraryResult> libraries);
```

Then we'd need `.dart_tool/build/entrypoint/build.dart` to make the list of builders public.  
And maybe a way to generate that `entrypoint/build.dart` in watch mode, without it starting builders.

That would enable third-party programs to manually trigger build_runner.

**Comment by jakemac53** [comment]
The `build` apis are generally built to enable people to build this type of thing, and I would be fully in support of such a thing existing, but we don't have bandwidth to support it officially.

It doesn't sound like you want to actually use build_runner to me, but instead build a different system which is purely driven from user requests to build files, and the analysis server (possibly this could be an analyzer plugin?). It wouldn't worry about whether the inputs to those files are themselves up to date etc. And it would use the already present resolved libraries from the analysis server.

Most of the high cost of build_runner builds is around the dependency tracking for builders that use the analyzer, and even building a single file often takes much longer than you might hope because it also has to make sure all the transitive inputs to that file are up to date, even though for _most_ use cases that probably isn't necessary, its a hermetic build system that prioritizes consistency/correctness over speed. That isn't necessarily the right model for a lot of people.

The hardest part would be knowing which builders can be ran and how to run them, we could make some things from the `.dart_tool/build/entrypoint/build.dart` file public but it sounds to me like many users might want to avoid a dependency on `build_runner` at all. You could use the `build_config` package directly instead, combined with the `PackageGraph` class, to understand the available builders.

There would definitely be a lot of open questions here and a lot of work to get things all hooked up but I would be willing to assist with answering questions etc (and possibly helping with any new APIs if needed, definitely would be able to do some code reviews for PRs here).

**Comment by rrousselGit** [comment]
To be clear, I'd be more than happy to work on this if that's reasonable. I wanted to get the discussion going first.



> It doesn't sound like you want to actually use build_runner to me

Kind of. Folks want an alternative way to trigger code-gen other than the command line.   
The problem is that at the moment, using a different trigger mechanism requires making brand new code-generators.

Some folks effectively forked existing code generators to use a custom IDE extension instead.
But it's done on a per-code-generator basis, and the clone of the original code-generator is a bit unhealthy for the community.

So the idea would be to enable all code-generators to seamlessly work with both approaches by default.



> Most of the high cost of build_runner builds is around the dependency tracking for builders that use the analyzer

That's probably a different topic but: I wonder if code generators could optionally opt out of dependency tracking, or manually list a few specific libraries they want to watch?

The current default behavior is safe. But maybe it'd be worth offering a more complex but more efficient alternative.

>  You could use the build_config package directly instead, combined with the PackageGraph class, to understand the available builders.

That's probable. In the end, I'd want to generate that `/build/entrypoint/build.dart#builders` the same way. I'd only strip the `main`
Not sure how that'd work with `build_config` only. But I'd be happy doing that if there's an easy way :)

**Comment by jakemac53** [comment]
> Kind of. Folks want an alternative way to trigger code-gen other than the command line.
The problem is that at the moment, using a different trigger mechanism requires making brand new code-generators.

Note that we do also have the `build_daemon` package which allows programmatic builds. It is in a bit of a weird state because it doesn't coordinate well with the regular build_runner commands (because those don't use the daemon). But as long as you don't run build_runner commands while you are also running a daemon build, it should work fine.

> So the idea would be to enable all code-generators to seamlessly work with both approaches by default.

The core `build` apis are intended to be very general purpose to avoid forking being necessary - it would ideally be possible to make some glue code between the IDE extension and any Builder? That is the intended way for this type of thing to work, `Builder` etc are not specific to build_runner. Internally for instance we don't use build_runner at all, we have a very different setup that uses Bazel and some glue code, build_runner doesn't even exist internally. But we can use most Builders (although there are some additional constraints on AST access due to the compilation model).

> That's probably a different topic but: I wonder if code generators could optionally opt out of dependency tracking, or manually list a few specific libraries they want to watch?

I would love to just make this more efficient, but it's a large time investment, and it gets super complicated because the deps for a file are actually _phase dependent_ since some of the transitive deps might not exist in one phase and then be added later etc.

But, in any case I wouldn't be totally opposed to adding some sort of way to sidestep the normal tracking here. The problem is large enough that I think it is worth providing a less safe but opt in workaround, if we can demonstrate its effectiveness.

> That's probable. In the end, I'd want to generate that `/build/entrypoint/build.dart#builders` the same way. I'd only strip the `main`
> Not sure how that'd work with `build_config` only. But I'd be happy doing that if there's an easy way :)

Actually it looks like we do already export a library for essentially this, https://pub.dev/documentation/build_runner/latest/build_script_generate/findBuilderApplications.html.

**Comment by rrousselGit** [comment]
> t is in a bit of a weird state because it doesn't coordinate well with the regular build_runner commands (because those don't use the daemon). But as long as you don't run build_runner commands while you are also running a daemon build, it should work fine.

That should be fine. Although there doesn't seem to be much documentation about it. It'd be a bit hard for me to use it like this.
Any pointer on where to get started?

> I would love to just make this more efficient, but it's a large time investment, and it gets super complicated because the deps for a file are actually phase dependent since some of the transitive deps might not exist in one phase and then be added later etc.

Could you expand on this? I'm not sure what phases you're referring to. I'm mainly aware of the `generate` function.

**Comment by DanTup** [comment]
I'm not all that familiar with `pkg:build` so it's not clear to me exactly what's being asked of the IDEs here (or how what's being asked for differs from the "watch" mode in build_runner?).

I would suggest that any work is done in an IDE-agnostic way though, even if the IDE is driving it :-)

**Comment by jakemac53** [comment]
> Any pointer on where to get started?

Yeah this was written originally for internal use and wasn't well documented at the time, but the example shows some basic usage to get you started https://github.com/dart-lang/build/blob/master/build_daemon/example/example.dart.

Other than that you would just have to look at the [api docs](https://pub.dev/documentation/build_daemon/latest/index.html).

You would likely just want to totally disconnect the client between requests, so you would connect to the daemon, register a build target (using the build filters option to specify the exact files you want to build), call `startBuild`, and then when the first build completes close the client.

IIRC the `target` needs to be a top level directory, but I can't remember for sure, you could just try passing a full file path if building exactly one file.

> Could you expand on this? I'm not sure what phases you're referring to. I'm mainly aware of the `generate` function.

This is specific to build_runner - and it controls the ordering of builders and which inputs are available to them. There are _many_ phases, usually comprised of a single builder applied to all files in the package (technically, applied to a "target" but most packages have only one target).

The `runs_before`, and `required_inputs` toggles are things we use to create an ordering, otherwise it is somewhat arbitrary (but consistent, for a given version of build_runner).

**Comment by rrousselGit** [comment]
Thanks!

I'll try making a barebone VScode extension and see if I can get something running. I'll share my progress here and possibly ask for help if you don't mind.
