### ISSUE TITLE
Could build_runner provide a stacktrace when builders throw an exception?

### ISSUE THREAD

**Issue by rrousselGit** [dart-lang/build#3585]
Hello!

One inconvenience I've had for a while is, if a code-generator fails, no stacktrace is available.
That makes debugging quite difficult.
For example, I've received the following issue: https://github.com/rrousselGit/riverpod/issues/2798:

```
[...]
[SEVERE] riverpod_generator on lib/app/state/animation.viewmodel.dart (cached):

Stack Overflow
[SEVERE] riverpod_generator on lib/app/state/places_view.viewmodel.dart (cached):

Stack Overflow
[SEVERE] riverpod_generator on lib/app/state/selected.viewmodel.dart (cached):

Stack Overflow
[SEVERE] Failed after 178ms
```

The user provided their console logs. But the error by itself is unhelpful.

**Comment by jakemac53** [comment]
If you pass `-v` it should print the stack traces.

**Comment by rrousselGit** [comment]
The main issue is, I have no control over what issue authors write.

Take the issue linked for example: Besides asking for more information, I can't do much.

If stacktraces were included by default, when users report issues, I'd be much more likely to be able to fix the issue in a short time-frame.

**Comment by natebosch** [comment]
@jakemac53 - WDYT about printing the stack trace by default for subtypes of `Error`, but not `Exception`?

I think it's intended behavior that a builder author can throw an `Exception` with a nice `.toString()` and have it not print the stack trace without `-v`. As long as builder authors are following best practice and not using `Error` for this, then we can print stack traces for `Error` subtypes and expect most of them to be bugs in the implementation and not intentional build failures.

**Comment by jakemac53** [comment]
SGTM

**Comment by rrousselGit** [comment]
In that case we'd want to make InvalidSourceGenerationError to be an exception instead https://pub.dev/documentation/source_gen/latest/source_gen/InvalidGenerationSourceError-class.html

I think many code generators rely on it
