### ISSUE TITLE
Separately calling builders

### ISSUE THREAD

**Issue by Pingear** [dart-lang/build#3600]
Hi, I spent a lot of time looking for an answer, but couldn't find it in the documentation. In my project I wrote many different builders. Everyone generates one or another part of the code. And some should not be restarted when called again
  build_runner build. Can I selectively run the builder I need? For example, one command build_runner build -c permission_builder and another build_runner build -c entity_builder and so that when executing one command, files generated by another builder are not deleted?

**Comment by jakemac53** [comment]
We support [build filters](https://github.com/dart-lang/build/blob/master/docs/partial_builds.md).

You can't select just a certain builder to run, because if it depends on some files that have been invalidated, or the build as a whole has been invalidated, we would still need to regenerate any files depended on by the outputs you are asking to build.

**Comment by Pingear** [comment]
Thanks for the answer, but filters are not suitable for me, because I work mainly with .dart files and builders rely on annotations, on the basis of which they make decisions about actions. 
The problem was that files successfully generated by one builder should not be deleted when another builder is launched. I was looking for a way to run each builder separately by specifying the identifier of the builder I need when calling the build_runner build command.
I never found such functionality, instead I simply specify the **auto_apply: none** parameter in the **build.yaml** file in the builder settings, which has already done its job, thus simply turning it off.
Maybe it will be useful to someone.

**Comment by jakemac53** [comment]
> Thanks for the answer, but filters are not suitable for me, because I work mainly with .dart files and builders rely on annotations, on the basis of which they make decisions about actions.

Most builders have specific output extensions though, so you can target them based on the file extension.

> The problem was that files successfully generated by one builder should not be deleted when another builder is launched.

They will only be deleted if they need to be regenerated because they are out of date (some dependency changed).

> I never found such functionality, instead I simply specify the **auto_apply: none** parameter in the **build.yaml** file in the builder settings, which has already done its job, thus simply turning it off.

This will work to select specific builders but it will also invalidate the entire build when you change it afaik. If that works for you then that is a fine approach though.
