### ISSUE TITLE
Error with build_runner: Type 'InvalidType' not found in generated file

### ISSUE THREAD

**Issue by AzPsu** [dart-lang/build#3673]
Hi devs,

I'm encountering an issue when trying to generate code via build_runner in my Flutter project. The error message I'm seeing is:

My Env:
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.19.6, on macOS 14.3.1 23D60 darwin-arm64, locale en-SA)
[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.2)
[✓] VS Code (version 1.87.0)
[✓] Connected device (3 available)            
[✓] Network resources
```

Error:
```
lib/stores/home.g.dart:51:3: Error: Type 'InvalidType' not found.
```

This error occurs inconsistently and I'm not sure why it's happening. I'd appreciate any insights or suggestions on how to resolve this issue.

Thank you.

**Comment by jakemac53** [comment]
Hi, sorry this issue slipped through the cracks.

In general this means that a code generator tried to emit code for a type which wasn't valid (couldn't be resolved somehow). Without more information I can't help to understand _why_ it might have been invalid, you could look at the generated code to try and understand what the type should have been.

This could be because some other generator hasn't generated the type yet, as an example.
