### ISSUE TITLE
`dart run build_runner build` Precompile build script failure (Flutter v3.24.0 ONLY)

### ISSUE THREAD

**Issue by kNoAPP** [dart-lang/build#3733]
Issue present after Flutter 3.24.0:
```
[INFO] Generating build script...
[INFO] Generating build script completed, took 406ms

[INFO] Precompiling build script......
Could not find a command named "/opt/hostedtoolcache/flutter/stable-3.24.0-x64/bin/cache/dart-sdk/bin/snapshots/frontend_server.dart.snapshot".

Usage: dart <command|dart-file> [arguments]

Global options:
-v, --verbose               Show additional command output.
    --version               Print the Dart SDK version.
    --enable-analytics      Enable analytics.
    --disable-analytics     Disable analytics.
    --suppress-analytics    Disallow analytics for this `dart *` run without changing the analytics configuration.
-h, --help                  Print this usage information.

Available commands:
  analyze    Analyze Dart code in a directory.
  compile    Compile Dart to various formats.
  create     Create a new Dart project.
  devtools   Open DevTools (optionally connecting to an existing application).
  doc        Generate API documentation for Dart projects.
  fix        Apply automated fixes to Dart source code.
  format     Idiomatically format Dart source code.
  info       Show diagnostic information about the installed tooling.
  pub        Work with packages.
  run        Run a Dart program.
  test       Run tests for a project.

Run "dart help <command>" for more information about a command.
See https://dart.dev/tools/dart-tool for detailed documentation.
[INFO] Precompiling build script... completed, took 126ms

[SEVERE] Failed to precompile build script .dart_tool/build/entrypoint/build.dart.
This is likely caused by a misconfigured builder definition.

Error: Process completed with exit code 78.
```
Ran via GitHub Actions, was working fine at Flutter 3.22.0 and earlier.

**Comment by jakemac53** [comment]
@kNoAPP I believe this is the result of having an outdated `frontend_server_client` package (this is a transitive dependency, you won't have it in your own pubspec).

Can you run a `flutter pub upgrade`? Or, you can try adding `frontend_server_client: ^4.0.0` to your `dependencies` in your pubspec.

If you are already on version 4.0.0 please let me know and I can investigate further.

**Comment by kNoAPP** [comment]
@jakemac53 Works like a charm. Thank you.

**Comment by kero990** [comment]
@jakemac53 
Hello, I am currently facing a situation where simply upgrading `frontend_server_client` is not sufficient to resolve the issue.  
The project is from the well-known repository [rustdesk/rustdesk](https://github.com/rustdesk/rustdesk). The project encounters the aforementioned error when using `flutter_rust_bridge_codegen`, as it fails to locate `frontend_server.dart.snapshot`.  
Simply updating `frontend_server.dart.snapshot` and `build_runner` does not resolve the issue.  
Directly using `flutter pub upgrade` can solve the problem, but it is too disruptive, and subsequent compilations encounter numerous issues.  

From the official CI, on x86, they use the normal compilation process, but on arm64, they use cached artifacts of `flutter_rust_bridge_codegen` instead of generating them in real-time. It is speculated that this issue may only be reproducible in the arm64 environment.  

Of course, based on the circumstances, it is possible that another package, not `build_runner`, is causing this result. Therefore, this information is shared for reference purposes only.

**Comment by jakemac53** [comment]
@kero990 sorry I missed your comment earlier

Are you still experiencing an issue here? I don't fully understand the nuance of what you are describing, and it likely isn't directly related to package:build, but I could help point you to somebody who can help if you still need it?

**Comment by jakemac53** [comment]
> Directly using flutter pub upgrade can solve the problem, but it is too disruptive, and subsequent compilations encounter numerous issues.

Most likely, you will just need to fix whatever those other issues are. It is a requirement to at least get frontend_server_client version 4.0.0, for newer SDKs. The frontend server snapshot file no longer exists and a different file has to be ran instead (I can't remember the exact details but if you need them I could dig it up).

**Comment by SirObi** [comment]
In case it helps anyone, I updated `frontend_server_client` to `4.0.0`, ran `flutter pub get` and the build command still failed, but subsequently running `flutter clean && flutter pub cache clean && flutter pub get` solved the issue.

**Comment by theamanthakur** [comment]
I'm still facing the issue, I updated frontend_server_client to 4.0.0, ran flutter pub get and the build command still failed, also tried running flutter clean && flutter pub cache clean && flutter pub get.

I used build_runner: ^2.4.13, and ^2.4.7

Building package executable... (1.9s)
Built build_runner:build_runner.
[INFO] Generating build script completed, took 180ms
```
[WARNING] ../.pub-cache/hosted/pub.dev/flutter_gen_core-5.9.0/lib/flutter_generator.dart:37:38: Error: Member not found: 'latestLanguageVersion'.
      languageVersion: DartFormatter.latestLanguageVersion,
                                     ^^^^^^^^^^^^^^^^^^^^^
../.pub-cache/hosted/pub.dev/flutter_gen_core-5.9.0/lib/flutter_generator.dart:37:7: Error: No named parameter with the name 'languageVersion'.
      languageVersion: DartFormatter.latestLanguageVersion,
      ^^^^^^^^^^^^^^^
../.pub-cache/hosted/pub.dev/dart_style-2.3.2/lib/src/dart_formatter.dart:51:3: Context: Found this candidate, but the arguments don't match.
  DartFormatter(
  ^^^^^^^^^^^^^
```
[INFO] Precompiling build script... completed, took 2.4s
[SEVERE] Failed to precompile build script .dart_tool/build/entrypoint/build.dart.
This is likely caused by a misconfigured builder definition.

**Comment by theamanthakur** [comment]
@davidmorgan thank you for quick response. I solved this problem by adding flutter_gen_core: 5.3.2 in dev dependency. 

Version incompatibility between flutter_gen_runner and transitive flutter_gen_core.
By default, dependency resolution picked a newer flutter_gen_core (5.9.0)
which was incompatible with dart_style (likely 2.3.2, SDK related).
Setting flutter_gen_core: 5.3.2 forces dependency resolver to use
a compatible version set with flutter_gen_runner: ^5.3.2, resolving
"Member not found: 'latestLanguageVersion'" and related errors.
This ensures version compatibility by overriding transitive dependency resolution.
