### ISSUE TITLE
Overhaul the serve method - write a Handler backed by the asset graph

### ISSUE THREAD

**Issue by natebosch** [dart-lang/build#384]
We need to be able to do some path translation for assets that would come from locations on disk other than their apparent path.

The [comment](https://github.com/dart-lang/build/blob/dead012b3590c76d7575b24723afb490a04aa3b3/build_runner/lib/src/generate/build.dart#L129-L131) is misleading here. We talk about overriding the `requestHandler` to get a different behavior than a server on `address:port` - but this happens regardless. The "custom behavior" you can override is reading files from disk - you can't change how they are served. We have a bug where we don't properly pass through `requestHandler`, but this is fine - changing that isn't something we'd want to support anyway. If anything we should have our request handler go through 

I think we should change our signature to something like:

```dart
abstract class BuildHandler {
  Stream<BuildResult> get builds;
  Future<Reponse> handle(Request request);
}
BuildHandler buildHandler(...);
```

Usage like:

```dart
import 'package:shelf/shelf.dart';
import 'package:build_runner/build_runner.dart;

import 'phases.dart';

void main() {
  // Here `serve` is coming from package:shelf rather than package:build_runner
  serve(buildHandler(phases).handle, address, port);
}
```

**Comment by jakemac53** [comment]
This generally SGTM, we probably want to change the `builds` stream to actually be a Stream of some other class that wraps a `Future<BuildResult>` or similar so that you can know when builds start and finish as opposed to just when they finish.

Alternatively it could be a `Stream<BuildEvent>` which could be an abstract class with `BuildStart` and `BuildEnd` implementations (`BuildEnd` would then add the `BuildResult` field)? That would potentially give us more flexibility (`BuildStart` for instance could expose a set of invalidated assets).

**Comment by natebosch** [comment]
The `handle` method would take care of blocking requests during builds. Are there other use cases for knowing the start/stop of builds?

I'm on board with either approach if we have a use case for exposing that info.

**Comment by jakemac53** [comment]
One potential use case would be exposing a widget which gave you the current build status in the browser. I think many custom integrations would want to know build information though, and adding in the extension point for more info in the future should help reduce churn.

**Comment by matanlurey** [comment]
Yuuuuuuuge 👍 on `BuildEvent` for custom integrations later on.
