### ISSUE TITLE
Create build_scratch package

### ISSUE THREAD

**Issue by natebosch** [dart-lang/build#397]
@jakemac53  added some nice utilities in `pub` for the DDC integration around managing temp directories.

We need something similar for DDC in build_runner, and it could also be useful for other Builder instances where we need to run binaries that don't quite fit the model - for instance wrapping SASS.

**Comment by natebosch** [comment]
We might also consider an interface on top of `AssetReader` and `AssetWriter`, or something tightly integrated with `build_runner` so that file invalidation can be done automatically.

**Comment by jakemac53** [comment]
Generally this sounds good, I think integrating it with build_runner should simplify/unify things greatly and also help people create other builders more correctly/efficiently in the future.

I do have a few questions/suggestions:

- What does `scratchPool.lease` do?
- Imo `scratch.linkWrites` should return a Future and immediately check for all expected outputs and copy them back, so it would move to after `Process.run`. That should simplify the logic a bit I think and clarify the behavior.
- What happens if an executable writes additional files? Do we ever clean those up?
- Do you envision a single shared scratch space, or should be give users more control (allow them to create their own scratch space, or possibly use a shared one). Shared ones are more risky in some ways but also more efficient.
- Would we want to persist scratch spaces across builds, or create a new one at the start of each build?

**Comment by natebosch** [comment]
> What does `scratchPool.lease` do?

I was imagining a pool model and `lease` would take ownership of one of the directories until the build was done. I'd also be fine hiding away the details of pooling and use `await ScratchSpace.create()` or similar.

> Imo `scratch.linkWrites` should return a Future and immediately check for all expected outputs and copy them back, so it would move to after `Process.run`. That should simplify the logic a bit I think and clarify the behavior.

I agree, I was imagining something where we'd have a directory watcher and write files though automatically without naming them, but that seems like a bad idea. We probably want the `Builder` to explicitly call out the assets it wants to use from the directory.

> What happens if an executable writes additional files? Do we ever clean those up?

Yeah I think by default we'll want 100% isolation. Temp directories are either removed entirely or are cleared out between `build` calls. If we want to get more optimized within `build_runner` we can look at ways to add hooks to replace the default functionality with something more clever.

> Do you envision a single shared scratch space, or should we give users more control (allow them to create their own scratch space, or possibly use a shared one). Shared ones are more risky in some ways but also more efficient.

> Would we want to persist scratch spaces across builds, or create a new one at the start of each build?

We should start with no sharing for safety, and then decide later on if we need to optimize and how. As we discussed offline we might be able to give a better isolation model in Linux than Windows, or maybe we can safe a "slow but safe" mode you can run in to ensure good behavior before switching to the fast and unsafe mode with some sharing.

**Comment by natebosch** [comment]
After some more discussion we don't want to expose this as a general purpose thing.

We're going to have to do some fairly dangerous stuff for DDC and Analyzer and we don't really want to expose that as a practice, nor will a safer general purpose scratch directory utility be very helpful for those workers.
