### ISSUE TITLE
Signal when builds are happening

### ISSUE THREAD

**Issue by natebosch** [dart-lang/build#400]
Today `watch` and `serve` return a `Stream<BuildResult>`. In https://github.com/dart-lang/build/issues/384 we considered changing it to `Stream<Future<BuildResult>>` or `Stream<BuildEvent>` where the event is either a `BuildStart` or `BuildEnd`.

I think we should also consider

```dart
class BuildResults {
  /// The current build if any is running.
  Future<BuildResult> currentBuild;
  Stream<BuildResult> builds;
}
```

This is most directly satisfies the "block if a build is happening" case and doesn't require a `where` and `map` to get back to `Stream<BuildResult>`. If it turns out to be necessary we can also add a `Stream<Null> buildStarts` without a breaking change.

**Comment by kevmoo** [comment]
`Stream<Future<BuildResult>>` makes me 🤢 – still the plan?

**Comment by natebosch** [comment]
My current PR goes with the class that has a `Future<BuildResult>` for the active build and a  `Stream<BuildResult>`. If you want to advocate instead for `Stream<BuildEvent>` with start and stop events we can also explore that further.

**Comment by kevmoo** [comment]
Just no stream of future :-)

From mobile. Sorry for brevity and/or spelling.

**Comment by jakemac53** [comment]
I like wrapping everything up in a single class which we can return an instance of from the various top level methods. That makes it easier for us to provide some convenience methods and additional information later on.

I would rename the `builds` getter to `buildResults` just so it is more specific and makes more sense later on if/when we do add other streams.

In the future I think `BuildResult` should probably extend a base `BuildEvent` class as opposed to being a separate object because that makes it easier to provide a single `Stream<BuildEvent>`, but that could happen if/when we decide to add a stream of `BuildStart` events.

**Comment by natebosch** [comment]
Once we publish the latest build_runner `watch` will return a class with this information.
