### ISSUE TITLE
Support separating build artifacts by a hash of the BuildActions rather than the entrypoint

### ISSUE THREAD

**Issue by natebosch** [dart-lang/build#588]
Spawned from a discussion around a use case where the BuildActions are set up dynamically based on arguments to the build script which causes the AssetGraph to change on each invocation and causes errors.

Filing an issue for discussion - it's not clear that this is something we want to support.

Two options I can see:

1. ~~Replace the entrypoint hash with a hash built from the BuildActions. This would isolate the builds entirely.~~
    - ~~In the case of `buildToCache: true` this would be safe - though suboptimal in that previously built artifacts would not be shareable even if we wanted to. This is analogous to having multiple bazel builds with different configurations.~~
   - ~~The the case of `buildToCache: false` this is risky. Generated outputs from one build would look like sources to another build and there would be unfortunate feedback loops~~
2. Use a separate hash from the BuildActions only when storing the AssetGraph. Builds are not isolated and could step on eachothers toes, this is risky regardless of `buildToCache`.
   - Do we need to disallow the same output from showing up in multiple AssetGraphs?
   - Would we need to prevent reads to generated files which were not generated within this specific AssetGraph? Otherwise we end up with the same feedback loops as `buildToCache: false` above - non-determinism would be very likely since it could start to matter which order you run builds in.

cc @eernstg

**Comment by jakemac53** [comment]
> Replace the entrypoint hash with a hash built from the BuildActions. This would isolate the builds entirely.

We would have to create generated files in their own hash based directory as well, which would make analyzer integration more difficult and/or impossible.

**Comment by natebosch** [comment]
Ah good point - we want to keep a single directory for the generated files

We currently have a hole today where separate build entrypoints can have separate AssetGraphs and we lose some of the safety of using the AssetGraph to enforce deterministic builds. I think this is mitigated with `buildToCache: true` since an AssetGraph which doesn't output a file can't see that file at all (even as a source). We do still have issues if the same output shows up in two graphs - this is something we probably want to resolve.

I'm definitely nervous about opening that hole wider from multiple entrypoints to an explicitly supported way to split out AssetGraphs.

**Comment by eernstg** [comment]
The setup I had in mind would make overlapping sets of generated files an error, so there should be no need to maintain "more than one version" of a generated file (so you don't need to think "let's put them into different directories" or anything like that).

If each asset graph specifies for each output which libraries it depends on, and stores enough information about the depended-upon libraries to be able to see whether anything changed such that the output must be re-generated, then code generation tasks can be rather independent: A set of code generation tasks that have non-overlapping outputs and where no output of any code generation task is a dependency for any other code generation task can be run in any order, and the need to regenerate code can be assessed for each code generation task in isolation.

If some outputs are used as inputs for other code generation tasks then we'd need a phase division: A task Ti can only take as input an output from Tj if Tj is in a strictly earlier phase than Ti. I don't know whether this kind of dependency is possible/common/important today, or how expensive it would be to introduce a notion of phases like that (in terms of developer management and comprehension, and in terms of building times) if it doesn't exist already, but it's clearly possible to (1) forbid this type of output-is-also-input dependency, or (2) allow it, and introduce phases.

It might be a problem (with several asset_graph.json files in one package) that there is some redundancy. But since each library would need to be characterized (in order to see whether something has been modified since the last time code was generated), I don't really think it is very redundant: Code generation for compartment 1 happened at a different time than for compartment 2, so they need to store different information about how the world looked at code generation time such that they can correctly detect whether re-generation is required.

**Comment by natebosch** [comment]
I think if we consider adding restrictions we'd have to look at two of them:

1. No two sets of BuildActions may output the same file.
2. No set of BuildActions may read a file output by another set.

With these restrictions we don't *really* have separate AssetGraphs per build, we have a single AssetGraph which is segmented in terms of visibility.

If we disallow cross-subset reads we would have strange order dependencies. If I build "Foo" first then "Bar" might fail, but all our customer might see is "I get an error when I build 'Bar' but my coworker can build it successfully".

If we allow cross-subset reads we would need to know the entire graph for all compartments from the first build. Then we'd either need to be statically informed of the order of builds to know what restrictions to put in place, or we'd need to write a solver to figure it out automatically.

We do have a notion of visibility restriction by phase. The inputs to the system are an ordered `List<BuildAction>` and no action may read a file which is generated by an action later in the list. The important thing here is we expect to know this list up front (which is where we're getting into the problems discussed here when we dynamically change that list).

It's not clear to me that these additional concepts, and additional complexity, allow us to solve any problems we couldn't solve before. What we end up with is a large single asset graph with additional restrictions and user behavior ordering dependencies. This also makes us deviate significantly from bazel since there is no concept of separate dependency graphs (other than statically configured visibility rules).

If we instead require the entire graph on the first build and focus on filtering what gets built (the way bazel does - asking for an output and building everything necessary to produce that output) then we remove user behavior ordering dependencies and don't need new concepts in the graph.

**Comment by natebosch** [comment]
Long term were moving more towards a
