### ISSUE TITLE
Allow declareOutputs to be async

### ISSUE THREAD

**Issue by donny-dont** [dart-lang/build#60]
One of my potential inputs to build is metadata in the form of a JSON schema or Swagger (OpenAPI). What will be output is not actually known until parsing the file(s).

Not sure if I'm just thinking about things wrong with how you'd use build so any other options are appreciated.

**Comment by jakemac53** [comment]
It is intentional today that we don't let you read inputs in `declareOutputs`, because that phase is designed to run very quickly, and it sometimes runs more than once per build (it is used to establish the dependency graph initially).

What you can do is over declare outputs (you aren't required to output the files that you declare). Is that enough for your use case?

**Comment by jakemac53** [comment]
Another option is to read in some config file and loading that info into the Builder itself before calling build/watch/serve etc. However, if you do that then you need to somehow notify the `build` package that the builder has a dependency on those files so that builds get invalidated when the schema changes.

**Comment by jakemac53** [comment]
Yet another option, would be to allow you to declare a file pattern as outputs instead of explicit files, so for instance you could return `['models/*.dart']`. This would mean that no other builders could output any files matching that though. Would this solve your use case?

**Comment by donny-dont** [comment]
I think the file pattern as outputs would be the best option. Its recommended that you put the different outputs into different directories so I think that would do the trick.

**Comment by jakemac53** [comment]
Ok so just to be clear, you have a single schema file which can result in multiple dart files with arbitrary names that cannot be computed based on that input file name alone? If this is the case then I think the solution seems reasonable, although it does present some potential issues.

**Comment by jakemac53** [comment]
cc @kevmoo

**Comment by donny-dont** [comment]
Let me give you a high level of what happens in dogma. For every library that can be generated there are two required bits of information for the build. The src directory, this is where all the individual libraries are outputted, and the root library which just exports the contents of the src directory.

The src directory is scanned for any user defined libraries. It checks for this by opening the file and determines if it was user defined or generated by a previous step. If its user defined then the file is analyzed and data is collected on it. A user could do this to provide an additional function for the conversion, for example if the API you were hitting used seconds since epoch to represent DateTime, or to totally override the behavior, like providing a hand rolled model instead of using the one that would be generated.

The different libraries are generated off of a pipeline. There are really two steps per library the generation of the metadata and the writing of the code. So to generate the Decoder/Encoder pair for a library the metadata for the model is read and then converted into metadata for a converter. It then generates the actual code from those two definitions.

In the case of the models being hand rolled there is a 1-1 ratio for files. But in the case of a JSON schema there could be 1 file mapping to some N files. So yea a matcher would be ideal for those cases.

**Comment by jakemac53** [comment]
It sounds like in this case you should just create a single dart output file, which contains all the classes defined in the schema file (instead of splitting it up). This makes it more clear where the dart file came from, and it also sidesteps the speed concerns related to the possible solutions I have provided here.

**Comment by jakemac53** [comment]
After some more thinking on this I am going to close it as not planned, simply due to the need to maintain compatibility with `bazel`. The current (although not ideal) recommendation would be to provide some configuration to your builder which tells it explicitly which files will be output for any given inputs, and then use that in `declareOutputs`.
