### ISSUE TITLE
Update the logs every <interval> as a heartbeat

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/build#641]
i.e. 

```
 ... still running (8 minutes so far)
 ... still running (9 minutes so far)
```

This is important because some CI environments (and some users, like me) consider no output via stdout/err within an interval of time to be a hung build/process, and are considered a failure. Anecdotally [travis fails after 10 minutes](https://travis-ci.org/dart-lang/angular/jobs/305529279).

My advice would be to emit a message at least every 1 minute.

This can probably just be the default without an opt-out/manual configuration for now.

**Comment by jakemac53** [comment]
I think I am going to try out just increasing the logging in general. Essentially log every time a phase starts or a lazy build starts.

In the console this doesn't get very spammy in practice because for info logs we bash over the previous line whenever we log anyways, and it gives a better signal that stuff is happening.

**Comment by jakemac53** [comment]
Hmm ran into some issues with long lines wrapping so we don't properly overwrite so this can get pretty spammy actually, and I don't think its worth trying to deal with that right now, will leave this open and we can just do the normal heartbeat as originally suggested

**Comment by natebosch** [comment]
Is there any way to tell the width of the terminal and truncate long lines?

**Comment by jakemac53** [comment]
Yes there is but it gets complicated because of non-visible characters - I don't think its worth putting the time into it right now.
