### ISSUE TITLE
Update golden file of generated builder

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/build#644]
Due to `code_builder` release.

https://travis-ci.org/dart-lang/build/jobs/305653945

**Comment by natebosch** [comment]
We'll need to stop running that test on the stable SDK since it can't pick up the latest code_builder.

Pretty soon we'll need to bump the min SDK for build_runner, but I'd like to get another 0.6.x release out before we do that. I'm hoping to nail down the interface of `BuilderFactory` so we can start transitioning build scripts from `BuildAction` -> `BuilderApplication` while on the 0.6.x branch.

**Comment by matanlurey** [comment]
Ah owch. I'll unassign for the time being since this is blocked.

I imagine we don't need to run on the stable SDK anymore anyway.

**Comment by matanlurey** [comment]
Blocked on https://github.com/dart-lang/build/issues/645.
