### ISSUE TITLE
Allow mixed-mode building

### ISSUE THREAD

**Issue by natebosch** [dart-lang/build#647]
We need to allow running Builders that output to source, as well as to the generated cache directory.

- [ ] #626 - How will outputting to source impact ordering? The Builders that output to source should probably all be run before those writing to the cache. They also likely shouldn't be allowed to use `required_inputs`
- [x] Store `isHidden` on `GeneratedAssetNode`. Use this to determine where to read from
- [x] Add `hiddenOutput` to `BuildAction`. We may want to hide this until `BuildAction` is removed from the public interface.
- [x] Support setting `hiddenOutput` through `BuilderApplication`.
- [x] Support some configuration for `hide_outputs` in `build.yaml`
- [x] Deprecate then drop `writeToCache` argument, use the per-action setting instead

**Comment by jakemac53** [comment]
SGTM, the only part I am not 100% sure on is enforcing ordering between source/cache dir outputs. I think the source dir outputs should typically go first but I think we will likely need the flexibility to support it either way.

**Comment by natebosch** [comment]
IMO a Builder outputting to source directory should not be able to read generated outputs. I will need to add that restriction to my prototype.

If a to-source builder can't read the outputs of a to-hidden builder, but reads can go in the other direction, I don't think it would ever make sense to run a to-hidden builder first.

**Comment by jakemac53** [comment]
Ideally transient files would always be generated in the hidden dir I think though, which would mean that to-source builders can't use transient files at all.

**Comment by natebosch** [comment]
I think we can handle transient files differently and still allow reads to them. We can have an enum with `transient`, `hidden`, or `sourceDir` maybe?

**Comment by jakemac53** [comment]
That could work.. but maybe its fine to just not allow it.

To me it makes sense that source dir outputs can't read other hidden dir outputs because the implication is that you are baking in some knowledge about how you currently see the world and shipping a file that depends on that, which could actually be different for some other user consuming your package. In that sense maybe it also makes sense to not allow reading of transient files... or maybe just not reading transient files from outside of your package but even those could end up with built-in dependencies on things that might change.
