### ISSUE TITLE
Caching between travis builds?

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/build#820]
https://github.com/dart-lang/build/blob/86fa08da81a87f2da6e21bc91e85f2dbdbbb124e/.travis.yml#L77

Didn't we used to do that?

**Comment by jakemac53** [comment]
Are you talking about the actual build scripts being cached? The only package in here using the cache dir version of build scripts is the e2e_example but we intentionally bash away the cache in the tests because we expect specific outputs/logs in the tests that might not appear if we did an incremental build.

**Comment by kevmoo** [comment]
Ah! was looking for an example.

Maybe I should set it up w/ json_serializable? Hrm...

**Comment by jakemac53** [comment]
fwiw, I think all you need is:

```yaml
cache:
 directories:
   - .dart_tool
```
