### ISSUE TITLE
Add detailed timing breakdown

### ISSUE THREAD

**Issue by alorenzen** [dart-lang/build#915]
For debugging purposes, it would be nice if we could have some sort of per-task breakdown of the build timing.
This could help us see the critical path and prioritize what to optimize.

**Comment by jakemac53** [comment]
This is unfortunately quite difficult because of the async (and lazy in some cases) nature of the builds. One approach is to allow builder authors to do their own tracking - as filed in https://github.com/dart-lang/build/issues/823.

This allows authors to track a bit more specifically the things they care about but it still doesn't solve the problem of accidentally tracking the time spent doing completely unrelated things during async gaps.

**Comment by matanlurey** [comment]
I think #823 is a good start.

It should be possible to tell total-time from `build()` to `build()` complete, right?

**Comment by jakemac53** [comment]
> It should be possible to tell total-time from build() to build() complete, right?

Yes - but unfortunately if you have any lazy inputs the number  you get back would not be meaningful in any way because its doing an arbitrary amount of unrelated work.
