### ISSUE TITLE
Waiting for builds is scary, no useful messages displayed

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/build#982]
Contrast with Bazel, where you potentially get _too_ much information.

Some ideas:
* During `heartbeat`, write the current action processing (so we can see it change)
* Print more information in general (similar to Bazel), i.e. building X from Y
* Give package-level progress updates (Finished <Builder> for package:<Name>)

**Comment by jakemac53** [comment]
Ya, we definitely want to do better here.

**Comment by jakemac53** [comment]
For now I am going to go with a simple approach of changing the heartbeat message to also display the number of actions completed versus started, for example:

`[INFO] Heartbeat: 58.7s elapsed, 3881/4099 actions completed.`

At the same time I am decreasing the time interval for the heartbeat to 1 second so you see this more often.

Note that the larger number is just the number of actions we have actually started building, so it will increase over time.

WDYT @matanlurey @natebosch ?

Reasoning for not doing the other suggestions:

> During heartbeat, write the current action processing (so we can see it change)

There are often many hundreds (or even thousands) of actions processing at a time, across phases.

> Print more information in general (similar to Bazel), i.e. building X from Y

We could do this, but it is extremely spammy and not actually that relevant, for the same reason that there are actually many actions running at once.

> Give package-level progress updates (Finished for package:)

Because of the lazy phases and things this isn't really feasible, or would require more work than its worth.

**Comment by matanlurey** [comment]
@jakemac53 SGTM, total actions reasonable.
